(cl:in-package car_interfaces-msg)
(cl:export '(NAV_FLAG-VAL
          NAV_FLAG
          X_ACC-VAL
          X_ACC
          Y_ACC-VAL
          Y_ACC
          X_GYRO-VAL
          X_GYRO
          Y_GYRO-VAL
          Y_GYRO
          Z_ACC-VAL
          Z_ACC
          Z_GYRO-VAL
          Z_GYRO
          ACC-VAL
          ACC
          GPS_WEEK-VAL
          GPS_WEEK
          GPS_MS-VAL
          GPS_MS
          NAV_FLAG_G-VAL
          NAV_FLAG_G
          HEADER-VAL
          HEADER
          GPS_TIME-VAL
          GPS_TIME
          POSLON-VAL
          POSLON
          POSLAT-VAL
          POSLAT
          POSALT-VAL
          POSALT
          LAT_G-VAL
          LAT_G
          LON_G-VAL
          LON_G
          EAST_SPEED_G-VAL
          EAST_SPEED_G
          NORTH_SPEED_G-VAL
          NORTH_SPEED_G
          UP_SPEED_G-VAL
          UP_SPEED_G
          ALT_G-VAL
          ALT_G
          HEADING_G-VAL
          HEADING_G
          VELE-VAL
          VELE
          VELN-VAL
          VELN
          VELU-VAL
          VELU
          VEL-VAL
          VEL
          ANGLEHEADING-VAL
          ANGLEHEADING
          ANGLEPITCH-VAL
          ANGLEPITCH
          ANGLEROLL-VAL
          ANGLEROLL
          SYSTEM_STATE-VAL
          SYSTEM_STATE
          GPSNUMSATSUSED-VAL
          GPSNUMSATSUSED
          SATELLITE_STATUS-VAL
          SATELLITE_STATUS
          GPSAGE-VAL
          GPSAGE
          STATE-VAL
          STATE
          POSX-VAL
          POSX
          POSY-VAL
          POSY
          POSZ-VAL
          POSZ
          PROCESS_TIME-VAL
          PROCESS_TIME
          GPS_CFAULT-VAL
          GPS_CFAULT
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          YAW-VAL
          YAW
          VEL-VAL
          VEL
          LAT-VAL
          LAT
          LON-VAL
          LON
          STATE_NDT-VAL
          STATE_NDT
))