(cl:in-package car_interfaces-msg)
(cl:export '(ANGLE-VAL
          ANGLE
          ACC-VAL
          ACC
          OPEN_GAS-VAL
          OPEN_GAS
          DRIVE_MODE-VAL
          DRIVE_MODE
          EPOSTS-VAL
          EPOSTS
          GEAR-VAL
          GEAR
          CAR_SPEED-VAL
          CAR_SPEED
          MOTOR_TORQUE-VAL
          MOTOR_TORQUE
          YK_F-VAL
          YK_F
          YK_H-VAL
          YK_H
          FAULT1-VAL
          FAULT1
          FAULT2-VAL
          FAULT2
          FAULT3-VAL
          FAULT3
          FAULT4-VAL
          FAULT4
          MILEAGE-VAL
          MILEAGE
          BRAKE_PRESSURE-VAL
          BRAKE_PRESSURE
          LR_WHEELSPEED-VAL
          LR_WHEELSPEED
          RR_WHEELSPEED-VAL
          RR_WHEELSPEED
          SOC-VAL
          SOC
          CARSTS1-VAL
          CARSTS1
          CARSTS2-VAL
          CARSTS2
          LX_HIGHT-VAL
          LX_HIGHT
          PITCHING-VAL
          PITCHING
          TIME-VAL
          TIME
          LV_MAIN-VAL
          LV_MAIN
          LV_ZCODE-VAL
          LV_ZCODE
          LV_SUN-VAL
          LV_SUN
          CARSTARTSTATE-VAL
          CARSTARTSTATE
          VCU_SERVICE_VOLTAGE-VAL
          VCU_SERVICE_VOLTAGE
          VCU_STS-VAL
          VCU_STS
          FAULT-VAL
          FAULT
          FLAG_END_WIRE-VAL
          FLAG_END_WIRE
          MSG_FROM_WIRE_TO_PLAN-VAL
          MSG_FROM_WIRE_TO_PLAN
          CURRENT_LATERAL_MOVEMENT_POSITION-VAL
          CURRENT_LATERAL_MOVEMENT_POSITION
          CURRENT_CLAMP_WIDTH-VAL
          CURRENT_CLAMP_WIDTH
          NOW_CAR_SPEED-VAL
          NOW_CAR_SPEED
))