(cl:in-package car_interfaces-msg)
(cl:export '(CONF-VAL
          CONF
          CLASS_ID-VAL
          CLASS_ID
          TRACK_ID-VAL
          TRACK_ID
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          L_X-VAL
          L_X
          L_Y-VAL
          L_Y
          L_Z-VAL
          L_Z
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          YAW-VAL
          YAW
          DEGREE-VAL
          DEGREE
          DISTANCE-VAL
          DISTANCE
          HEIGHT-VAL
          HEIGHT
          TARGET_WIDTH-VAL
          TARGET_WIDTH
          TARGET_HEIGHT-VAL
          TARGET_HEIGHT
          LEFT_BOUDARY_POINT-VAL
          LEFT_BOUDARY_POINT
          RIGHT_BOUDARY_POINT-VAL
          RIGHT_BOUDARY_POINT
          TOP_BOUDARY_POINT-VAL
          TOP_BOUDARY_POINT
))