(cl:in-package car_interfaces-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          TARGET_VELOCITY-VAL
          TARGET_VELOCITY
          TARGET_STEERING_ANGLE-VAL
          TARGET_STEERING_ANGLE
          TARGET_GEAR-VAL
          TARGET_GEAR
          TARGET_PRIMARY_GEAR-VAL
          TARGET_PRIMARY_GEAR
          TARGET_ENGINESPEEDLEVEL-VAL
          TARGET_ENGINESPEEDLEVEL
          TARGET_SPEEDLEVER_PERCENTAGE-VAL
          TARGET_SPEEDLEVER_PERCENTAGE
          TARGET_TORQUE_NM-VAL
          TARGET_TORQUE_NM
          TARGET_BRAKING_PERCENTAGE-VAL
          TARGET_BRAKING_PERCENTAGE
          NEARESTPOINT_CAR2PATH-VAL
          NEARESTPOINT_CAR2PATH
          COTTON_BIN_CTRL-VAL
          COTTON_BIN_CTRL
          CTE-VAL
          CTE
          DHEAD-VAL
          DHEAD
          BRAKE_ENABLE-VAL
          BRAKE_ENABLE
          VALUE_BRAKE-VAL
          VALUE_BRAKE
          FLAG-VAL
          FLAG
          UPDOWN-VAL
          UPDOWN
          RAW_CONTROL-VAL
          RAW_CONTROL
          KAPPA-VAL
          KAPPA
          X_TRAJECTORY-VAL
          X_TRAJECTORY
          Y_TRAJECTORY-VAL
          Y_TRAJECTORY
          GEAR-VAL
          GEAR
          ACTION-VAL
          ACTION
          FY_POSITION-VAL
          FY_POSITION
          FY-VAL
          FY
          IPC_EN-VAL
          IPC_EN
          UPDOWN_POSITION-VAL
          UPDOWN_POSITION
          FLAG_CAMERA-VAL
          FLAG_CAMERA
))