# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from car_interfaces/CarOriInterface.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CarOriInterface(genpy.Message):
  _md5sum = "d4f6f01de7b91510a86389a083d89da5"
  _type = "car_interfaces/CarOriInterface"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 Angle  # 方向盘转角反馈
float64 Acc #加速度
float64 open_gas #油门踏板开度
int8 Drive_Mode #驾驶模式
int8 EPOSts #急停
int8 Gear #档位 
float64 Car_Speed #车速
float64 Motor_Torque #油门反馈
int8 YK_F #复位H
int8 YK_H #遥控F

int8 Fault1 # 故障代码1  
int8 Fault2 # 故障代码2  
int8 Fault3 # # 故障代码3  
int8 Fault4 # # 故障代码4  
float64 Mileage # 累计里程

float32 Brake_Pressure #制动压力采样值
float32 LR_WheelSpeed  
float32 RR_WheelSpeed   
float32 SOC   # SOC
int8 CarSts1   # 车辆状态1
int8 CarSts2   # 车辆状态2

float64 LX_Hight # 高度传感器
float64 Pitching   # 俯仰传感器

float64 Time # 日期
int8 LV_Main   # 主版本
int8 LV_zCode   # 子版本
int8 LV_Sun   # 修订版本

int8 CarStartState # 车辆启动状态
float32 VCU_Service_Voltage   # VCU供电电压
int32 VCU_Sts   # VCU状态
int8 Fault   # 整车故障

int8 flag_end_wire # 线控反馈局部终点到达情况
int8 msg_from_wire_to_plan

float64 current_lateral_movement_position  #横移
float64 current_clamp_width #夹抱宽度
float64 now_car_speed #0-100km/h 单位不一样和Car_Speed"""
  __slots__ = ['Angle','Acc','open_gas','Drive_Mode','EPOSts','Gear','Car_Speed','Motor_Torque','YK_F','YK_H','Fault1','Fault2','Fault3','Fault4','Mileage','Brake_Pressure','LR_WheelSpeed','RR_WheelSpeed','SOC','CarSts1','CarSts2','LX_Hight','Pitching','Time','LV_Main','LV_zCode','LV_Sun','CarStartState','VCU_Service_Voltage','VCU_Sts','Fault','flag_end_wire','msg_from_wire_to_plan','current_lateral_movement_position','current_clamp_width','now_car_speed']
  _slot_types = ['float64','float64','float64','int8','int8','int8','float64','float64','int8','int8','int8','int8','int8','int8','float64','float32','float32','float32','float32','int8','int8','float64','float64','float64','int8','int8','int8','int8','float32','int32','int8','int8','int8','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Angle,Acc,open_gas,Drive_Mode,EPOSts,Gear,Car_Speed,Motor_Torque,YK_F,YK_H,Fault1,Fault2,Fault3,Fault4,Mileage,Brake_Pressure,LR_WheelSpeed,RR_WheelSpeed,SOC,CarSts1,CarSts2,LX_Hight,Pitching,Time,LV_Main,LV_zCode,LV_Sun,CarStartState,VCU_Service_Voltage,VCU_Sts,Fault,flag_end_wire,msg_from_wire_to_plan,current_lateral_movement_position,current_clamp_width,now_car_speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CarOriInterface, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Angle is None:
        self.Angle = 0.
      if self.Acc is None:
        self.Acc = 0.
      if self.open_gas is None:
        self.open_gas = 0.
      if self.Drive_Mode is None:
        self.Drive_Mode = 0
      if self.EPOSts is None:
        self.EPOSts = 0
      if self.Gear is None:
        self.Gear = 0
      if self.Car_Speed is None:
        self.Car_Speed = 0.
      if self.Motor_Torque is None:
        self.Motor_Torque = 0.
      if self.YK_F is None:
        self.YK_F = 0
      if self.YK_H is None:
        self.YK_H = 0
      if self.Fault1 is None:
        self.Fault1 = 0
      if self.Fault2 is None:
        self.Fault2 = 0
      if self.Fault3 is None:
        self.Fault3 = 0
      if self.Fault4 is None:
        self.Fault4 = 0
      if self.Mileage is None:
        self.Mileage = 0.
      if self.Brake_Pressure is None:
        self.Brake_Pressure = 0.
      if self.LR_WheelSpeed is None:
        self.LR_WheelSpeed = 0.
      if self.RR_WheelSpeed is None:
        self.RR_WheelSpeed = 0.
      if self.SOC is None:
        self.SOC = 0.
      if self.CarSts1 is None:
        self.CarSts1 = 0
      if self.CarSts2 is None:
        self.CarSts2 = 0
      if self.LX_Hight is None:
        self.LX_Hight = 0.
      if self.Pitching is None:
        self.Pitching = 0.
      if self.Time is None:
        self.Time = 0.
      if self.LV_Main is None:
        self.LV_Main = 0
      if self.LV_zCode is None:
        self.LV_zCode = 0
      if self.LV_Sun is None:
        self.LV_Sun = 0
      if self.CarStartState is None:
        self.CarStartState = 0
      if self.VCU_Service_Voltage is None:
        self.VCU_Service_Voltage = 0.
      if self.VCU_Sts is None:
        self.VCU_Sts = 0
      if self.Fault is None:
        self.Fault = 0
      if self.flag_end_wire is None:
        self.flag_end_wire = 0
      if self.msg_from_wire_to_plan is None:
        self.msg_from_wire_to_plan = 0
      if self.current_lateral_movement_position is None:
        self.current_lateral_movement_position = 0.
      if self.current_clamp_width is None:
        self.current_clamp_width = 0.
      if self.now_car_speed is None:
        self.now_car_speed = 0.
    else:
      self.Angle = 0.
      self.Acc = 0.
      self.open_gas = 0.
      self.Drive_Mode = 0
      self.EPOSts = 0
      self.Gear = 0
      self.Car_Speed = 0.
      self.Motor_Torque = 0.
      self.YK_F = 0
      self.YK_H = 0
      self.Fault1 = 0
      self.Fault2 = 0
      self.Fault3 = 0
      self.Fault4 = 0
      self.Mileage = 0.
      self.Brake_Pressure = 0.
      self.LR_WheelSpeed = 0.
      self.RR_WheelSpeed = 0.
      self.SOC = 0.
      self.CarSts1 = 0
      self.CarSts2 = 0
      self.LX_Hight = 0.
      self.Pitching = 0.
      self.Time = 0.
      self.LV_Main = 0
      self.LV_zCode = 0
      self.LV_Sun = 0
      self.CarStartState = 0
      self.VCU_Service_Voltage = 0.
      self.VCU_Sts = 0
      self.Fault = 0
      self.flag_end_wire = 0
      self.msg_from_wire_to_plan = 0
      self.current_lateral_movement_position = 0.
      self.current_clamp_width = 0.
      self.now_car_speed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d3b2d6bd4f2b3d4bfi3b3d().pack(_x.Angle, _x.Acc, _x.open_gas, _x.Drive_Mode, _x.EPOSts, _x.Gear, _x.Car_Speed, _x.Motor_Torque, _x.YK_F, _x.YK_H, _x.Fault1, _x.Fault2, _x.Fault3, _x.Fault4, _x.Mileage, _x.Brake_Pressure, _x.LR_WheelSpeed, _x.RR_WheelSpeed, _x.SOC, _x.CarSts1, _x.CarSts2, _x.LX_Hight, _x.Pitching, _x.Time, _x.LV_Main, _x.LV_zCode, _x.LV_Sun, _x.CarStartState, _x.VCU_Service_Voltage, _x.VCU_Sts, _x.Fault, _x.flag_end_wire, _x.msg_from_wire_to_plan, _x.current_lateral_movement_position, _x.current_clamp_width, _x.now_car_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 138
      (_x.Angle, _x.Acc, _x.open_gas, _x.Drive_Mode, _x.EPOSts, _x.Gear, _x.Car_Speed, _x.Motor_Torque, _x.YK_F, _x.YK_H, _x.Fault1, _x.Fault2, _x.Fault3, _x.Fault4, _x.Mileage, _x.Brake_Pressure, _x.LR_WheelSpeed, _x.RR_WheelSpeed, _x.SOC, _x.CarSts1, _x.CarSts2, _x.LX_Hight, _x.Pitching, _x.Time, _x.LV_Main, _x.LV_zCode, _x.LV_Sun, _x.CarStartState, _x.VCU_Service_Voltage, _x.VCU_Sts, _x.Fault, _x.flag_end_wire, _x.msg_from_wire_to_plan, _x.current_lateral_movement_position, _x.current_clamp_width, _x.now_car_speed,) = _get_struct_3d3b2d6bd4f2b3d4bfi3b3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d3b2d6bd4f2b3d4bfi3b3d().pack(_x.Angle, _x.Acc, _x.open_gas, _x.Drive_Mode, _x.EPOSts, _x.Gear, _x.Car_Speed, _x.Motor_Torque, _x.YK_F, _x.YK_H, _x.Fault1, _x.Fault2, _x.Fault3, _x.Fault4, _x.Mileage, _x.Brake_Pressure, _x.LR_WheelSpeed, _x.RR_WheelSpeed, _x.SOC, _x.CarSts1, _x.CarSts2, _x.LX_Hight, _x.Pitching, _x.Time, _x.LV_Main, _x.LV_zCode, _x.LV_Sun, _x.CarStartState, _x.VCU_Service_Voltage, _x.VCU_Sts, _x.Fault, _x.flag_end_wire, _x.msg_from_wire_to_plan, _x.current_lateral_movement_position, _x.current_clamp_width, _x.now_car_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 138
      (_x.Angle, _x.Acc, _x.open_gas, _x.Drive_Mode, _x.EPOSts, _x.Gear, _x.Car_Speed, _x.Motor_Torque, _x.YK_F, _x.YK_H, _x.Fault1, _x.Fault2, _x.Fault3, _x.Fault4, _x.Mileage, _x.Brake_Pressure, _x.LR_WheelSpeed, _x.RR_WheelSpeed, _x.SOC, _x.CarSts1, _x.CarSts2, _x.LX_Hight, _x.Pitching, _x.Time, _x.LV_Main, _x.LV_zCode, _x.LV_Sun, _x.CarStartState, _x.VCU_Service_Voltage, _x.VCU_Sts, _x.Fault, _x.flag_end_wire, _x.msg_from_wire_to_plan, _x.current_lateral_movement_position, _x.current_clamp_width, _x.now_car_speed,) = _get_struct_3d3b2d6bd4f2b3d4bfi3b3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d3b2d6bd4f2b3d4bfi3b3d = None
def _get_struct_3d3b2d6bd4f2b3d4bfi3b3d():
    global _struct_3d3b2d6bd4f2b3d4bfi3b3d
    if _struct_3d3b2d6bd4f2b3d4bfi3b3d is None:
        _struct_3d3b2d6bd4f2b3d4bfi3b3d = struct.Struct("<3d3b2d6bd4f2b3d4bfi3b3d")
    return _struct_3d3b2d6bd4f2b3d4bfi3b3d
