# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from car_interfaces/Object.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Object(genpy.Message):
  _md5sum = "693ea0c1d42830af046c93ddc187f2b2"
  _type = "car_interfaces/Object"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 conf            # 得分
float32 class_id        # 类别
float32 track_id	    # 跟踪id
float32 x               # 全局 相对加+车辆定位  单位m
float32 y	            # 全局 相对加+车辆定位  单位m
float32 z	            # 全局 相对加+车辆定位  单位m
float32 l_x	            # 相对 单位m
float32 l_y	            # 相对 单位m
float32 l_z	            # 相对 单位m
float32 pitch	        # unit:rad,关于车辆坐标系z轴角度+车辆pitch 
float32 roll	        # unit:rad,关于车辆坐标系y轴角度+车辆roll 
float32 yaw	            # unit:rad,degree+车辆航向 yaw 
float32 degree	        # 角度,车辆坐标系x轴夹角 
float32 distance	    # 单位m
float32 height	        # 单位m
float32 target_width    # 单位m
float32 target_height   # 单位m
float32[] left_boudary_point
float32[] right_boudary_point
float32[] top_boudary_point"""
  __slots__ = ['conf','class_id','track_id','x','y','z','l_x','l_y','l_z','pitch','roll','yaw','degree','distance','height','target_width','target_height','left_boudary_point','right_boudary_point','top_boudary_point']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32[]','float32[]','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       conf,class_id,track_id,x,y,z,l_x,l_y,l_z,pitch,roll,yaw,degree,distance,height,target_width,target_height,left_boudary_point,right_boudary_point,top_boudary_point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Object, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.conf is None:
        self.conf = 0.
      if self.class_id is None:
        self.class_id = 0.
      if self.track_id is None:
        self.track_id = 0.
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.l_x is None:
        self.l_x = 0.
      if self.l_y is None:
        self.l_y = 0.
      if self.l_z is None:
        self.l_z = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.roll is None:
        self.roll = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.degree is None:
        self.degree = 0.
      if self.distance is None:
        self.distance = 0.
      if self.height is None:
        self.height = 0.
      if self.target_width is None:
        self.target_width = 0.
      if self.target_height is None:
        self.target_height = 0.
      if self.left_boudary_point is None:
        self.left_boudary_point = []
      if self.right_boudary_point is None:
        self.right_boudary_point = []
      if self.top_boudary_point is None:
        self.top_boudary_point = []
    else:
      self.conf = 0.
      self.class_id = 0.
      self.track_id = 0.
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.l_x = 0.
      self.l_y = 0.
      self.l_z = 0.
      self.pitch = 0.
      self.roll = 0.
      self.yaw = 0.
      self.degree = 0.
      self.distance = 0.
      self.height = 0.
      self.target_width = 0.
      self.target_height = 0.
      self.left_boudary_point = []
      self.right_boudary_point = []
      self.top_boudary_point = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_17f().pack(_x.conf, _x.class_id, _x.track_id, _x.x, _x.y, _x.z, _x.l_x, _x.l_y, _x.l_z, _x.pitch, _x.roll, _x.yaw, _x.degree, _x.distance, _x.height, _x.target_width, _x.target_height))
      length = len(self.left_boudary_point)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.left_boudary_point))
      length = len(self.right_boudary_point)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.right_boudary_point))
      length = len(self.top_boudary_point)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.top_boudary_point))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 68
      (_x.conf, _x.class_id, _x.track_id, _x.x, _x.y, _x.z, _x.l_x, _x.l_y, _x.l_z, _x.pitch, _x.roll, _x.yaw, _x.degree, _x.distance, _x.height, _x.target_width, _x.target_height,) = _get_struct_17f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.left_boudary_point = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.right_boudary_point = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.top_boudary_point = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_17f().pack(_x.conf, _x.class_id, _x.track_id, _x.x, _x.y, _x.z, _x.l_x, _x.l_y, _x.l_z, _x.pitch, _x.roll, _x.yaw, _x.degree, _x.distance, _x.height, _x.target_width, _x.target_height))
      length = len(self.left_boudary_point)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.left_boudary_point.tostring())
      length = len(self.right_boudary_point)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.right_boudary_point.tostring())
      length = len(self.top_boudary_point)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.top_boudary_point.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 68
      (_x.conf, _x.class_id, _x.track_id, _x.x, _x.y, _x.z, _x.l_x, _x.l_y, _x.l_z, _x.pitch, _x.roll, _x.yaw, _x.degree, _x.distance, _x.height, _x.target_width, _x.target_height,) = _get_struct_17f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.left_boudary_point = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.right_boudary_point = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.top_boudary_point = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_17f = None
def _get_struct_17f():
    global _struct_17f
    if _struct_17f is None:
        _struct_17f = struct.Struct("<17f")
    return _struct_17f
