# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from car_interfaces/RoadList.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import car_interfaces.msg

class RoadList(genpy.Message):
  _md5sum = "9b41673bd6f78e4df2d5e654099939f0"
  _type = "car_interfaces/RoadList"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Pathplan[] paths
int8 path_length
float32[] end_points
float32[] dis_every_end
================================================================================
MSG: car_interfaces/Pathplan
Pointplan[] points
================================================================================
MSG: car_interfaces/Pointplan
float64 x
float64 y
float64 yaw
float64 speed
float64 kappa
int8 gear

"""
  __slots__ = ['paths','path_length','end_points','dis_every_end']
  _slot_types = ['car_interfaces/Pathplan[]','int8','float32[]','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       paths,path_length,end_points,dis_every_end

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RoadList, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.paths is None:
        self.paths = []
      if self.path_length is None:
        self.path_length = 0
      if self.end_points is None:
        self.end_points = []
      if self.dis_every_end is None:
        self.dis_every_end = []
    else:
      self.paths = []
      self.path_length = 0
      self.end_points = []
      self.dis_every_end = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.paths)
      buff.write(_struct_I.pack(length))
      for val1 in self.paths:
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          _x = val2
          buff.write(_get_struct_5db().pack(_x.x, _x.y, _x.yaw, _x.speed, _x.kappa, _x.gear))
      _x = self.path_length
      buff.write(_get_struct_b().pack(_x))
      length = len(self.end_points)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.end_points))
      length = len(self.dis_every_end)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.dis_every_end))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.paths is None:
        self.paths = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.paths = []
      for i in range(0, length):
        val1 = car_interfaces.msg.Pathplan()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = car_interfaces.msg.Pointplan()
          _x = val2
          start = end
          end += 41
          (_x.x, _x.y, _x.yaw, _x.speed, _x.kappa, _x.gear,) = _get_struct_5db().unpack(str[start:end])
          val1.points.append(val2)
        self.paths.append(val1)
      start = end
      end += 1
      (self.path_length,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.end_points = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.dis_every_end = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.paths)
      buff.write(_struct_I.pack(length))
      for val1 in self.paths:
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          _x = val2
          buff.write(_get_struct_5db().pack(_x.x, _x.y, _x.yaw, _x.speed, _x.kappa, _x.gear))
      _x = self.path_length
      buff.write(_get_struct_b().pack(_x))
      length = len(self.end_points)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.end_points.tostring())
      length = len(self.dis_every_end)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.dis_every_end.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.paths is None:
        self.paths = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.paths = []
      for i in range(0, length):
        val1 = car_interfaces.msg.Pathplan()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = car_interfaces.msg.Pointplan()
          _x = val2
          start = end
          end += 41
          (_x.x, _x.y, _x.yaw, _x.speed, _x.kappa, _x.gear,) = _get_struct_5db().unpack(str[start:end])
          val1.points.append(val2)
        self.paths.append(val1)
      start = end
      end += 1
      (self.path_length,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.end_points = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.dis_every_end = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5db = None
def _get_struct_5db():
    global _struct_5db
    if _struct_5db is None:
        _struct_5db = struct.Struct("<5db")
    return _struct_5db
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
