# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from car_interfaces/single_task.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class single_task(genpy.Message):
  _md5sum = "cd39bd39ec0bd232a174cb3a0b3c77c0"
  _type = "car_interfaces/single_task"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string task_id
int32 bale_num_to_handle
string destination_shelf_area
geometry_msgs/Pose origin_shelf_job_position
geometry_msgs/Pose destination_shelf_job_position
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['task_id','bale_num_to_handle','destination_shelf_area','origin_shelf_job_position','destination_shelf_job_position']
  _slot_types = ['string','int32','string','geometry_msgs/Pose','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       task_id,bale_num_to_handle,destination_shelf_area,origin_shelf_job_position,destination_shelf_job_position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(single_task, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.task_id is None:
        self.task_id = ''
      if self.bale_num_to_handle is None:
        self.bale_num_to_handle = 0
      if self.destination_shelf_area is None:
        self.destination_shelf_area = ''
      if self.origin_shelf_job_position is None:
        self.origin_shelf_job_position = geometry_msgs.msg.Pose()
      if self.destination_shelf_job_position is None:
        self.destination_shelf_job_position = geometry_msgs.msg.Pose()
    else:
      self.task_id = ''
      self.bale_num_to_handle = 0
      self.destination_shelf_area = ''
      self.origin_shelf_job_position = geometry_msgs.msg.Pose()
      self.destination_shelf_job_position = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.task_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.bale_num_to_handle
      buff.write(_get_struct_i().pack(_x))
      _x = self.destination_shelf_area
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_14d().pack(_x.origin_shelf_job_position.position.x, _x.origin_shelf_job_position.position.y, _x.origin_shelf_job_position.position.z, _x.origin_shelf_job_position.orientation.x, _x.origin_shelf_job_position.orientation.y, _x.origin_shelf_job_position.orientation.z, _x.origin_shelf_job_position.orientation.w, _x.destination_shelf_job_position.position.x, _x.destination_shelf_job_position.position.y, _x.destination_shelf_job_position.position.z, _x.destination_shelf_job_position.orientation.x, _x.destination_shelf_job_position.orientation.y, _x.destination_shelf_job_position.orientation.z, _x.destination_shelf_job_position.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.origin_shelf_job_position is None:
        self.origin_shelf_job_position = geometry_msgs.msg.Pose()
      if self.destination_shelf_job_position is None:
        self.destination_shelf_job_position = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.task_id = str[start:end]
      start = end
      end += 4
      (self.bale_num_to_handle,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.destination_shelf_area = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.destination_shelf_area = str[start:end]
      _x = self
      start = end
      end += 112
      (_x.origin_shelf_job_position.position.x, _x.origin_shelf_job_position.position.y, _x.origin_shelf_job_position.position.z, _x.origin_shelf_job_position.orientation.x, _x.origin_shelf_job_position.orientation.y, _x.origin_shelf_job_position.orientation.z, _x.origin_shelf_job_position.orientation.w, _x.destination_shelf_job_position.position.x, _x.destination_shelf_job_position.position.y, _x.destination_shelf_job_position.position.z, _x.destination_shelf_job_position.orientation.x, _x.destination_shelf_job_position.orientation.y, _x.destination_shelf_job_position.orientation.z, _x.destination_shelf_job_position.orientation.w,) = _get_struct_14d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.task_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.bale_num_to_handle
      buff.write(_get_struct_i().pack(_x))
      _x = self.destination_shelf_area
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_14d().pack(_x.origin_shelf_job_position.position.x, _x.origin_shelf_job_position.position.y, _x.origin_shelf_job_position.position.z, _x.origin_shelf_job_position.orientation.x, _x.origin_shelf_job_position.orientation.y, _x.origin_shelf_job_position.orientation.z, _x.origin_shelf_job_position.orientation.w, _x.destination_shelf_job_position.position.x, _x.destination_shelf_job_position.position.y, _x.destination_shelf_job_position.position.z, _x.destination_shelf_job_position.orientation.x, _x.destination_shelf_job_position.orientation.y, _x.destination_shelf_job_position.orientation.z, _x.destination_shelf_job_position.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.origin_shelf_job_position is None:
        self.origin_shelf_job_position = geometry_msgs.msg.Pose()
      if self.destination_shelf_job_position is None:
        self.destination_shelf_job_position = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.task_id = str[start:end]
      start = end
      end += 4
      (self.bale_num_to_handle,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.destination_shelf_area = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.destination_shelf_area = str[start:end]
      _x = self
      start = end
      end += 112
      (_x.origin_shelf_job_position.position.x, _x.origin_shelf_job_position.position.y, _x.origin_shelf_job_position.position.z, _x.origin_shelf_job_position.orientation.x, _x.origin_shelf_job_position.orientation.y, _x.origin_shelf_job_position.orientation.z, _x.origin_shelf_job_position.orientation.w, _x.destination_shelf_job_position.position.x, _x.destination_shelf_job_position.position.y, _x.destination_shelf_job_position.position.z, _x.destination_shelf_job_position.orientation.x, _x.destination_shelf_job_position.orientation.y, _x.destination_shelf_job_position.orientation.z, _x.destination_shelf_job_position.orientation.w,) = _get_struct_14d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_14d = None
def _get_struct_14d():
    global _struct_14d
    if _struct_14d is None:
        _struct_14d = struct.Struct("<14d")
    return _struct_14d
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
