# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from car_interfaces/TargetDetectionInterface.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import car_interfaces.msg
import std_msgs.msg

class TargetDetectionInterface(genpy.Message):
  _md5sum = "735eae5f7f43274afc03991f37962f29"
  _type = "car_interfaces/TargetDetectionInterface"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# topic : /lidar_camera_det/detections
# frame_id : velo_link
std_msgs/Header header  
Object[] objects

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: car_interfaces/Object
float32 conf            # 得分
float32 class_id        # 类别
float32 track_id	    # 跟踪id
float32 x               # 全局 相对加+车辆定位  单位m
float32 y	            # 全局 相对加+车辆定位  单位m
float32 z	            # 全局 相对加+车辆定位  单位m
float32 l_x	            # 相对 单位m
float32 l_y	            # 相对 单位m
float32 l_z	            # 相对 单位m
float32 pitch	        # unit:rad,关于车辆坐标系z轴角度+车辆pitch 
float32 roll	        # unit:rad,关于车辆坐标系y轴角度+车辆roll 
float32 yaw	            # unit:rad,degree+车辆航向 yaw 
float32 degree	        # 角度,车辆坐标系x轴夹角 
float32 distance	    # 单位m
float32 height	        # 单位m
float32 target_width    # 单位m
float32 target_height   # 单位m
float32[] left_boudary_point
float32[] right_boudary_point
float32[] top_boudary_point"""
  __slots__ = ['header','objects']
  _slot_types = ['std_msgs/Header','car_interfaces/Object[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,objects

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TargetDetectionInterface, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.objects is None:
        self.objects = []
    else:
      self.header = std_msgs.msg.Header()
      self.objects = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.objects:
        _x = val1
        buff.write(_get_struct_17f().pack(_x.conf, _x.class_id, _x.track_id, _x.x, _x.y, _x.z, _x.l_x, _x.l_y, _x.l_z, _x.pitch, _x.roll, _x.yaw, _x.degree, _x.distance, _x.height, _x.target_width, _x.target_height))
        length = len(val1.left_boudary_point)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*val1.left_boudary_point))
        length = len(val1.right_boudary_point)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*val1.right_boudary_point))
        length = len(val1.top_boudary_point)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*val1.top_boudary_point))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.objects is None:
        self.objects = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objects = []
      for i in range(0, length):
        val1 = car_interfaces.msg.Object()
        _x = val1
        start = end
        end += 68
        (_x.conf, _x.class_id, _x.track_id, _x.x, _x.y, _x.z, _x.l_x, _x.l_y, _x.l_z, _x.pitch, _x.roll, _x.yaw, _x.degree, _x.distance, _x.height, _x.target_width, _x.target_height,) = _get_struct_17f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.left_boudary_point = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.right_boudary_point = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.top_boudary_point = s.unpack(str[start:end])
        self.objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.objects:
        _x = val1
        buff.write(_get_struct_17f().pack(_x.conf, _x.class_id, _x.track_id, _x.x, _x.y, _x.z, _x.l_x, _x.l_y, _x.l_z, _x.pitch, _x.roll, _x.yaw, _x.degree, _x.distance, _x.height, _x.target_width, _x.target_height))
        length = len(val1.left_boudary_point)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(val1.left_boudary_point.tostring())
        length = len(val1.right_boudary_point)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(val1.right_boudary_point.tostring())
        length = len(val1.top_boudary_point)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(val1.top_boudary_point.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.objects is None:
        self.objects = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objects = []
      for i in range(0, length):
        val1 = car_interfaces.msg.Object()
        _x = val1
        start = end
        end += 68
        (_x.conf, _x.class_id, _x.track_id, _x.x, _x.y, _x.z, _x.l_x, _x.l_y, _x.l_z, _x.pitch, _x.roll, _x.yaw, _x.degree, _x.distance, _x.height, _x.target_width, _x.target_height,) = _get_struct_17f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.left_boudary_point = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.right_boudary_point = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.top_boudary_point = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        self.objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_17f = None
def _get_struct_17f():
    global _struct_17f
    if _struct_17f is None:
        _struct_17f = struct.Struct("<17f")
    return _struct_17f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
