// Generated by gencpp from file car_interfaces/BalesNumInCamera.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_BALESNUMINCAMERA_H
#define CAR_INTERFACES_MESSAGE_BALESNUMINCAMERA_H

#include <ros/service_traits.h>


#include <car_interfaces/BalesNumInCameraRequest.h>
#include <car_interfaces/BalesNumInCameraResponse.h>


namespace car_interfaces
{

struct BalesNumInCamera
{

typedef BalesNumInCameraRequest Request;
typedef BalesNumInCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BalesNumInCamera
} // namespace car_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_interfaces::BalesNumInCamera > {
  static const char* value()
  {
    return "208d4ab53cf12eb941a7d93b34b7532b";
  }

  static const char* value(const ::car_interfaces::BalesNumInCamera&) { return value(); }
};

template<>
struct DataType< ::car_interfaces::BalesNumInCamera > {
  static const char* value()
  {
    return "car_interfaces/BalesNumInCamera";
  }

  static const char* value(const ::car_interfaces::BalesNumInCamera&) { return value(); }
};


// service_traits::MD5Sum< ::car_interfaces::BalesNumInCameraRequest> should match
// service_traits::MD5Sum< ::car_interfaces::BalesNumInCamera >
template<>
struct MD5Sum< ::car_interfaces::BalesNumInCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::BalesNumInCamera >::value();
  }
  static const char* value(const ::car_interfaces::BalesNumInCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::BalesNumInCameraRequest> should match
// service_traits::DataType< ::car_interfaces::BalesNumInCamera >
template<>
struct DataType< ::car_interfaces::BalesNumInCameraRequest>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::BalesNumInCamera >::value();
  }
  static const char* value(const ::car_interfaces::BalesNumInCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_interfaces::BalesNumInCameraResponse> should match
// service_traits::MD5Sum< ::car_interfaces::BalesNumInCamera >
template<>
struct MD5Sum< ::car_interfaces::BalesNumInCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::BalesNumInCamera >::value();
  }
  static const char* value(const ::car_interfaces::BalesNumInCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::BalesNumInCameraResponse> should match
// service_traits::DataType< ::car_interfaces::BalesNumInCamera >
template<>
struct DataType< ::car_interfaces::BalesNumInCameraResponse>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::BalesNumInCamera >::value();
  }
  static const char* value(const ::car_interfaces::BalesNumInCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_BALESNUMINCAMERA_H
