// Generated by gencpp from file car_interfaces/CameraTask.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_CAMERATASK_H
#define CAR_INTERFACES_MESSAGE_CAMERATASK_H

#include <ros/service_traits.h>


#include <car_interfaces/CameraTaskRequest.h>
#include <car_interfaces/CameraTaskResponse.h>


namespace car_interfaces
{

struct CameraTask
{

typedef CameraTaskRequest Request;
typedef CameraTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraTask
} // namespace car_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_interfaces::CameraTask > {
  static const char* value()
  {
    return "208d4ab53cf12eb941a7d93b34b7532b";
  }

  static const char* value(const ::car_interfaces::CameraTask&) { return value(); }
};

template<>
struct DataType< ::car_interfaces::CameraTask > {
  static const char* value()
  {
    return "car_interfaces/CameraTask";
  }

  static const char* value(const ::car_interfaces::CameraTask&) { return value(); }
};


// service_traits::MD5Sum< ::car_interfaces::CameraTaskRequest> should match
// service_traits::MD5Sum< ::car_interfaces::CameraTask >
template<>
struct MD5Sum< ::car_interfaces::CameraTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::CameraTask >::value();
  }
  static const char* value(const ::car_interfaces::CameraTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::CameraTaskRequest> should match
// service_traits::DataType< ::car_interfaces::CameraTask >
template<>
struct DataType< ::car_interfaces::CameraTaskRequest>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::CameraTask >::value();
  }
  static const char* value(const ::car_interfaces::CameraTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_interfaces::CameraTaskResponse> should match
// service_traits::MD5Sum< ::car_interfaces::CameraTask >
template<>
struct MD5Sum< ::car_interfaces::CameraTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::CameraTask >::value();
  }
  static const char* value(const ::car_interfaces::CameraTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::CameraTaskResponse> should match
// service_traits::DataType< ::car_interfaces::CameraTask >
template<>
struct DataType< ::car_interfaces::CameraTaskResponse>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::CameraTask >::value();
  }
  static const char* value(const ::car_interfaces::CameraTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_CAMERATASK_H
