// Generated by gencpp from file car_interfaces/CarOriInterface.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_CARORIINTERFACE_H
#define CAR_INTERFACES_MESSAGE_CARORIINTERFACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_interfaces
{
template <class ContainerAllocator>
struct CarOriInterface_
{
  typedef CarOriInterface_<ContainerAllocator> Type;

  CarOriInterface_()
    : Angle(0.0)
    , Acc(0.0)
    , open_gas(0.0)
    , Drive_Mode(0)
    , EPOSts(0)
    , Gear(0)
    , Car_Speed(0.0)
    , Motor_Torque(0.0)
    , YK_F(0)
    , YK_H(0)
    , Fault1(0)
    , Fault2(0)
    , Fault3(0)
    , Fault4(0)
    , Mileage(0.0)
    , Brake_Pressure(0.0)
    , LR_WheelSpeed(0.0)
    , RR_WheelSpeed(0.0)
    , SOC(0.0)
    , CarSts1(0)
    , CarSts2(0)
    , LX_Hight(0.0)
    , Pitching(0.0)
    , Time(0.0)
    , LV_Main(0)
    , LV_zCode(0)
    , LV_Sun(0)
    , CarStartState(0)
    , VCU_Service_Voltage(0.0)
    , VCU_Sts(0)
    , Fault(0)
    , flag_end_wire(0)
    , msg_from_wire_to_plan(0)
    , current_lateral_movement_position(0.0)
    , current_clamp_width(0.0)
    , now_car_speed(0.0)  {
    }
  CarOriInterface_(const ContainerAllocator& _alloc)
    : Angle(0.0)
    , Acc(0.0)
    , open_gas(0.0)
    , Drive_Mode(0)
    , EPOSts(0)
    , Gear(0)
    , Car_Speed(0.0)
    , Motor_Torque(0.0)
    , YK_F(0)
    , YK_H(0)
    , Fault1(0)
    , Fault2(0)
    , Fault3(0)
    , Fault4(0)
    , Mileage(0.0)
    , Brake_Pressure(0.0)
    , LR_WheelSpeed(0.0)
    , RR_WheelSpeed(0.0)
    , SOC(0.0)
    , CarSts1(0)
    , CarSts2(0)
    , LX_Hight(0.0)
    , Pitching(0.0)
    , Time(0.0)
    , LV_Main(0)
    , LV_zCode(0)
    , LV_Sun(0)
    , CarStartState(0)
    , VCU_Service_Voltage(0.0)
    , VCU_Sts(0)
    , Fault(0)
    , flag_end_wire(0)
    , msg_from_wire_to_plan(0)
    , current_lateral_movement_position(0.0)
    , current_clamp_width(0.0)
    , now_car_speed(0.0)  {
  (void)_alloc;
    }



   typedef double _Angle_type;
  _Angle_type Angle;

   typedef double _Acc_type;
  _Acc_type Acc;

   typedef double _open_gas_type;
  _open_gas_type open_gas;

   typedef int8_t _Drive_Mode_type;
  _Drive_Mode_type Drive_Mode;

   typedef int8_t _EPOSts_type;
  _EPOSts_type EPOSts;

   typedef int8_t _Gear_type;
  _Gear_type Gear;

   typedef double _Car_Speed_type;
  _Car_Speed_type Car_Speed;

   typedef double _Motor_Torque_type;
  _Motor_Torque_type Motor_Torque;

   typedef int8_t _YK_F_type;
  _YK_F_type YK_F;

   typedef int8_t _YK_H_type;
  _YK_H_type YK_H;

   typedef int8_t _Fault1_type;
  _Fault1_type Fault1;

   typedef int8_t _Fault2_type;
  _Fault2_type Fault2;

   typedef int8_t _Fault3_type;
  _Fault3_type Fault3;

   typedef int8_t _Fault4_type;
  _Fault4_type Fault4;

   typedef double _Mileage_type;
  _Mileage_type Mileage;

   typedef float _Brake_Pressure_type;
  _Brake_Pressure_type Brake_Pressure;

   typedef float _LR_WheelSpeed_type;
  _LR_WheelSpeed_type LR_WheelSpeed;

   typedef float _RR_WheelSpeed_type;
  _RR_WheelSpeed_type RR_WheelSpeed;

   typedef float _SOC_type;
  _SOC_type SOC;

   typedef int8_t _CarSts1_type;
  _CarSts1_type CarSts1;

   typedef int8_t _CarSts2_type;
  _CarSts2_type CarSts2;

   typedef double _LX_Hight_type;
  _LX_Hight_type LX_Hight;

   typedef double _Pitching_type;
  _Pitching_type Pitching;

   typedef double _Time_type;
  _Time_type Time;

   typedef int8_t _LV_Main_type;
  _LV_Main_type LV_Main;

   typedef int8_t _LV_zCode_type;
  _LV_zCode_type LV_zCode;

   typedef int8_t _LV_Sun_type;
  _LV_Sun_type LV_Sun;

   typedef int8_t _CarStartState_type;
  _CarStartState_type CarStartState;

   typedef float _VCU_Service_Voltage_type;
  _VCU_Service_Voltage_type VCU_Service_Voltage;

   typedef int32_t _VCU_Sts_type;
  _VCU_Sts_type VCU_Sts;

   typedef int8_t _Fault_type;
  _Fault_type Fault;

   typedef int8_t _flag_end_wire_type;
  _flag_end_wire_type flag_end_wire;

   typedef int8_t _msg_from_wire_to_plan_type;
  _msg_from_wire_to_plan_type msg_from_wire_to_plan;

   typedef double _current_lateral_movement_position_type;
  _current_lateral_movement_position_type current_lateral_movement_position;

   typedef double _current_clamp_width_type;
  _current_clamp_width_type current_clamp_width;

   typedef double _now_car_speed_type;
  _now_car_speed_type now_car_speed;





  typedef boost::shared_ptr< ::car_interfaces::CarOriInterface_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::CarOriInterface_<ContainerAllocator> const> ConstPtr;

}; // struct CarOriInterface_

typedef ::car_interfaces::CarOriInterface_<std::allocator<void> > CarOriInterface;

typedef boost::shared_ptr< ::car_interfaces::CarOriInterface > CarOriInterfacePtr;
typedef boost::shared_ptr< ::car_interfaces::CarOriInterface const> CarOriInterfaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::CarOriInterface_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::CarOriInterface_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::CarOriInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::CarOriInterface_<ContainerAllocator2> & rhs)
{
  return lhs.Angle == rhs.Angle &&
    lhs.Acc == rhs.Acc &&
    lhs.open_gas == rhs.open_gas &&
    lhs.Drive_Mode == rhs.Drive_Mode &&
    lhs.EPOSts == rhs.EPOSts &&
    lhs.Gear == rhs.Gear &&
    lhs.Car_Speed == rhs.Car_Speed &&
    lhs.Motor_Torque == rhs.Motor_Torque &&
    lhs.YK_F == rhs.YK_F &&
    lhs.YK_H == rhs.YK_H &&
    lhs.Fault1 == rhs.Fault1 &&
    lhs.Fault2 == rhs.Fault2 &&
    lhs.Fault3 == rhs.Fault3 &&
    lhs.Fault4 == rhs.Fault4 &&
    lhs.Mileage == rhs.Mileage &&
    lhs.Brake_Pressure == rhs.Brake_Pressure &&
    lhs.LR_WheelSpeed == rhs.LR_WheelSpeed &&
    lhs.RR_WheelSpeed == rhs.RR_WheelSpeed &&
    lhs.SOC == rhs.SOC &&
    lhs.CarSts1 == rhs.CarSts1 &&
    lhs.CarSts2 == rhs.CarSts2 &&
    lhs.LX_Hight == rhs.LX_Hight &&
    lhs.Pitching == rhs.Pitching &&
    lhs.Time == rhs.Time &&
    lhs.LV_Main == rhs.LV_Main &&
    lhs.LV_zCode == rhs.LV_zCode &&
    lhs.LV_Sun == rhs.LV_Sun &&
    lhs.CarStartState == rhs.CarStartState &&
    lhs.VCU_Service_Voltage == rhs.VCU_Service_Voltage &&
    lhs.VCU_Sts == rhs.VCU_Sts &&
    lhs.Fault == rhs.Fault &&
    lhs.flag_end_wire == rhs.flag_end_wire &&
    lhs.msg_from_wire_to_plan == rhs.msg_from_wire_to_plan &&
    lhs.current_lateral_movement_position == rhs.current_lateral_movement_position &&
    lhs.current_clamp_width == rhs.current_clamp_width &&
    lhs.now_car_speed == rhs.now_car_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::CarOriInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::CarOriInterface_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::CarOriInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::CarOriInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::CarOriInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::CarOriInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::CarOriInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::CarOriInterface_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::CarOriInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4f6f01de7b91510a86389a083d89da5";
  }

  static const char* value(const ::car_interfaces::CarOriInterface_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4f6f01de7b91510ULL;
  static const uint64_t static_value2 = 0xa86389a083d89da5ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::CarOriInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/CarOriInterface";
  }

  static const char* value(const ::car_interfaces::CarOriInterface_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::CarOriInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 Angle  # 方向盘转角反馈\n"
"float64 Acc #加速度\n"
"float64 open_gas #油门踏板开度\n"
"int8 Drive_Mode #驾驶模式\n"
"int8 EPOSts #急停\n"
"int8 Gear #档位 \n"
"float64 Car_Speed #车速\n"
"float64 Motor_Torque #油门反馈\n"
"int8 YK_F #复位H\n"
"int8 YK_H #遥控F\n"
"\n"
"int8 Fault1 # 故障代码1  \n"
"int8 Fault2 # 故障代码2  \n"
"int8 Fault3 # # 故障代码3  \n"
"int8 Fault4 # # 故障代码4  \n"
"float64 Mileage # 累计里程\n"
"\n"
"float32 Brake_Pressure #制动压力采样值\n"
"float32 LR_WheelSpeed  \n"
"float32 RR_WheelSpeed   \n"
"float32 SOC   # SOC\n"
"int8 CarSts1   # 车辆状态1\n"
"int8 CarSts2   # 车辆状态2\n"
"\n"
"float64 LX_Hight # 高度传感器\n"
"float64 Pitching   # 俯仰传感器\n"
"\n"
"float64 Time # 日期\n"
"int8 LV_Main   # 主版本\n"
"int8 LV_zCode   # 子版本\n"
"int8 LV_Sun   # 修订版本\n"
"\n"
"int8 CarStartState # 车辆启动状态\n"
"float32 VCU_Service_Voltage   # VCU供电电压\n"
"int32 VCU_Sts   # VCU状态\n"
"int8 Fault   # 整车故障\n"
"\n"
"int8 flag_end_wire # 线控反馈局部终点到达情况\n"
"int8 msg_from_wire_to_plan\n"
"\n"
"float64 current_lateral_movement_position  #横移\n"
"float64 current_clamp_width #夹抱宽度\n"
"float64 now_car_speed #0-100km/h 单位不一样和Car_Speed\n"
;
  }

  static const char* value(const ::car_interfaces::CarOriInterface_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::CarOriInterface_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Angle);
      stream.next(m.Acc);
      stream.next(m.open_gas);
      stream.next(m.Drive_Mode);
      stream.next(m.EPOSts);
      stream.next(m.Gear);
      stream.next(m.Car_Speed);
      stream.next(m.Motor_Torque);
      stream.next(m.YK_F);
      stream.next(m.YK_H);
      stream.next(m.Fault1);
      stream.next(m.Fault2);
      stream.next(m.Fault3);
      stream.next(m.Fault4);
      stream.next(m.Mileage);
      stream.next(m.Brake_Pressure);
      stream.next(m.LR_WheelSpeed);
      stream.next(m.RR_WheelSpeed);
      stream.next(m.SOC);
      stream.next(m.CarSts1);
      stream.next(m.CarSts2);
      stream.next(m.LX_Hight);
      stream.next(m.Pitching);
      stream.next(m.Time);
      stream.next(m.LV_Main);
      stream.next(m.LV_zCode);
      stream.next(m.LV_Sun);
      stream.next(m.CarStartState);
      stream.next(m.VCU_Service_Voltage);
      stream.next(m.VCU_Sts);
      stream.next(m.Fault);
      stream.next(m.flag_end_wire);
      stream.next(m.msg_from_wire_to_plan);
      stream.next(m.current_lateral_movement_position);
      stream.next(m.current_clamp_width);
      stream.next(m.now_car_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarOriInterface_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::CarOriInterface_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::CarOriInterface_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "Angle: ";
    Printer<double>::stream(s, indent + "  ", v.Angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Acc: ";
    Printer<double>::stream(s, indent + "  ", v.Acc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "open_gas: ";
    Printer<double>::stream(s, indent + "  ", v.open_gas);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Drive_Mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Drive_Mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "EPOSts: ";
    Printer<int8_t>::stream(s, indent + "  ", v.EPOSts);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Gear: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Gear);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Car_Speed: ";
    Printer<double>::stream(s, indent + "  ", v.Car_Speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Motor_Torque: ";
    Printer<double>::stream(s, indent + "  ", v.Motor_Torque);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "YK_F: ";
    Printer<int8_t>::stream(s, indent + "  ", v.YK_F);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "YK_H: ";
    Printer<int8_t>::stream(s, indent + "  ", v.YK_H);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Fault1: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Fault1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Fault2: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Fault2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Fault3: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Fault3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Fault4: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Fault4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Mileage: ";
    Printer<double>::stream(s, indent + "  ", v.Mileage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Brake_Pressure: ";
    Printer<float>::stream(s, indent + "  ", v.Brake_Pressure);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "LR_WheelSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.LR_WheelSpeed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "RR_WheelSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.RR_WheelSpeed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "SOC: ";
    Printer<float>::stream(s, indent + "  ", v.SOC);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CarSts1: ";
    Printer<int8_t>::stream(s, indent + "  ", v.CarSts1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CarSts2: ";
    Printer<int8_t>::stream(s, indent + "  ", v.CarSts2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "LX_Hight: ";
    Printer<double>::stream(s, indent + "  ", v.LX_Hight);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Pitching: ";
    Printer<double>::stream(s, indent + "  ", v.Pitching);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Time: ";
    Printer<double>::stream(s, indent + "  ", v.Time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "LV_Main: ";
    Printer<int8_t>::stream(s, indent + "  ", v.LV_Main);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "LV_zCode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.LV_zCode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "LV_Sun: ";
    Printer<int8_t>::stream(s, indent + "  ", v.LV_Sun);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CarStartState: ";
    Printer<int8_t>::stream(s, indent + "  ", v.CarStartState);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "VCU_Service_Voltage: ";
    Printer<float>::stream(s, indent + "  ", v.VCU_Service_Voltage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "VCU_Sts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.VCU_Sts);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Fault: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Fault);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flag_end_wire: ";
    Printer<int8_t>::stream(s, indent + "  ", v.flag_end_wire);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "msg_from_wire_to_plan: ";
    Printer<int8_t>::stream(s, indent + "  ", v.msg_from_wire_to_plan);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_lateral_movement_position: ";
    Printer<double>::stream(s, indent + "  ", v.current_lateral_movement_position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_clamp_width: ";
    Printer<double>::stream(s, indent + "  ", v.current_clamp_width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "now_car_speed: ";
    Printer<double>::stream(s, indent + "  ", v.now_car_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_CARORIINTERFACE_H
