// Generated by gencpp from file car_interfaces/cloud_orderRequest.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_CLOUD_ORDERREQUEST_H
#define CAR_INTERFACES_MESSAGE_CLOUD_ORDERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <car_interfaces/single_task.h>

namespace car_interfaces
{
template <class ContainerAllocator>
struct cloud_orderRequest_
{
  typedef cloud_orderRequest_<ContainerAllocator> Type;

  cloud_orderRequest_()
    : header()
    , order_id()
    , task_info()  {
    }
  cloud_orderRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , order_id(_alloc)
    , task_info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _order_id_type;
  _order_id_type order_id;

   typedef std::vector< ::car_interfaces::single_task_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::car_interfaces::single_task_<ContainerAllocator> >> _task_info_type;
  _task_info_type task_info;





  typedef boost::shared_ptr< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct cloud_orderRequest_

typedef ::car_interfaces::cloud_orderRequest_<std::allocator<void> > cloud_orderRequest;

typedef boost::shared_ptr< ::car_interfaces::cloud_orderRequest > cloud_orderRequestPtr;
typedef boost::shared_ptr< ::car_interfaces::cloud_orderRequest const> cloud_orderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::cloud_orderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::cloud_orderRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::cloud_orderRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.order_id == rhs.order_id &&
    lhs.task_info == rhs.task_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::cloud_orderRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::cloud_orderRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77d0fa18394ac387ddeddd7414ed08bb";
  }

  static const char* value(const ::car_interfaces::cloud_orderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77d0fa18394ac387ULL;
  static const uint64_t static_value2 = 0xddeddd7414ed08bbULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/cloud_orderRequest";
  }

  static const char* value(const ::car_interfaces::cloud_orderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string order_id\n"
"single_task[] task_info\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: car_interfaces/single_task\n"
"string task_id\n"
"int32 bale_num_to_handle\n"
"string destination_shelf_area\n"
"geometry_msgs/Pose origin_shelf_job_position\n"
"geometry_msgs/Pose destination_shelf_job_position\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::car_interfaces::cloud_orderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.order_id);
      stream.next(m.task_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cloud_orderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::cloud_orderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::cloud_orderRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "order_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.order_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_info: ";
    if (v.task_info.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.task_info.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::car_interfaces::single_task_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.task_info[i]);
    }
    if (v.task_info.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_CLOUD_ORDERREQUEST_H
