// Generated by gencpp from file car_interfaces/cloud_order.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_CLOUD_ORDER_H
#define CAR_INTERFACES_MESSAGE_CLOUD_ORDER_H

#include <ros/service_traits.h>


#include <car_interfaces/cloud_orderRequest.h>
#include <car_interfaces/cloud_orderResponse.h>


namespace car_interfaces
{

struct cloud_order
{

typedef cloud_orderRequest Request;
typedef cloud_orderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cloud_order
} // namespace car_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_interfaces::cloud_order > {
  static const char* value()
  {
    return "2f612faf22d533382bbf07ab0d079f5c";
  }

  static const char* value(const ::car_interfaces::cloud_order&) { return value(); }
};

template<>
struct DataType< ::car_interfaces::cloud_order > {
  static const char* value()
  {
    return "car_interfaces/cloud_order";
  }

  static const char* value(const ::car_interfaces::cloud_order&) { return value(); }
};


// service_traits::MD5Sum< ::car_interfaces::cloud_orderRequest> should match
// service_traits::MD5Sum< ::car_interfaces::cloud_order >
template<>
struct MD5Sum< ::car_interfaces::cloud_orderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::cloud_order >::value();
  }
  static const char* value(const ::car_interfaces::cloud_orderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::cloud_orderRequest> should match
// service_traits::DataType< ::car_interfaces::cloud_order >
template<>
struct DataType< ::car_interfaces::cloud_orderRequest>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::cloud_order >::value();
  }
  static const char* value(const ::car_interfaces::cloud_orderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_interfaces::cloud_orderResponse> should match
// service_traits::MD5Sum< ::car_interfaces::cloud_order >
template<>
struct MD5Sum< ::car_interfaces::cloud_orderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::cloud_order >::value();
  }
  static const char* value(const ::car_interfaces::cloud_orderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::cloud_orderResponse> should match
// service_traits::DataType< ::car_interfaces::cloud_order >
template<>
struct DataType< ::car_interfaces::cloud_orderResponse>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::cloud_order >::value();
  }
  static const char* value(const ::car_interfaces::cloud_orderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_CLOUD_ORDER_H
