// Generated by gencpp from file car_interfaces/cloud_orderResponse.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_CLOUD_ORDERRESPONSE_H
#define CAR_INTERFACES_MESSAGE_CLOUD_ORDERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_interfaces
{
template <class ContainerAllocator>
struct cloud_orderResponse_
{
  typedef cloud_orderResponse_<ContainerAllocator> Type;

  cloud_orderResponse_()
    : task_progress(0.0)  {
    }
  cloud_orderResponse_(const ContainerAllocator& _alloc)
    : task_progress(0.0)  {
  (void)_alloc;
    }



   typedef float _task_progress_type;
  _task_progress_type task_progress;





  typedef boost::shared_ptr< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cloud_orderResponse_

typedef ::car_interfaces::cloud_orderResponse_<std::allocator<void> > cloud_orderResponse;

typedef boost::shared_ptr< ::car_interfaces::cloud_orderResponse > cloud_orderResponsePtr;
typedef boost::shared_ptr< ::car_interfaces::cloud_orderResponse const> cloud_orderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::cloud_orderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::cloud_orderResponse_<ContainerAllocator1> & lhs, const ::car_interfaces::cloud_orderResponse_<ContainerAllocator2> & rhs)
{
  return lhs.task_progress == rhs.task_progress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::cloud_orderResponse_<ContainerAllocator1> & lhs, const ::car_interfaces::cloud_orderResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f37f1ca867a358453a87f032439ada55";
  }

  static const char* value(const ::car_interfaces::cloud_orderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf37f1ca867a35845ULL;
  static const uint64_t static_value2 = 0x3a87f032439ada55ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/cloud_orderResponse";
  }

  static const char* value(const ::car_interfaces::cloud_orderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 task_progress\n"
;
  }

  static const char* value(const ::car_interfaces::cloud_orderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_progress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cloud_orderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::cloud_orderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::cloud_orderResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "task_progress: ";
    Printer<float>::stream(s, indent + "  ", v.task_progress);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_CLOUD_ORDERRESPONSE_H
