// Generated by gencpp from file car_interfaces/ControlTask.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_CONTROLTASK_H
#define CAR_INTERFACES_MESSAGE_CONTROLTASK_H

#include <ros/service_traits.h>


#include <car_interfaces/ControlTaskRequest.h>
#include <car_interfaces/ControlTaskResponse.h>


namespace car_interfaces
{

struct ControlTask
{

typedef ControlTaskRequest Request;
typedef ControlTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControlTask
} // namespace car_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_interfaces::ControlTask > {
  static const char* value()
  {
    return "b2af9fa50c34b99733809c3ac7fab044";
  }

  static const char* value(const ::car_interfaces::ControlTask&) { return value(); }
};

template<>
struct DataType< ::car_interfaces::ControlTask > {
  static const char* value()
  {
    return "car_interfaces/ControlTask";
  }

  static const char* value(const ::car_interfaces::ControlTask&) { return value(); }
};


// service_traits::MD5Sum< ::car_interfaces::ControlTaskRequest> should match
// service_traits::MD5Sum< ::car_interfaces::ControlTask >
template<>
struct MD5Sum< ::car_interfaces::ControlTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::ControlTask >::value();
  }
  static const char* value(const ::car_interfaces::ControlTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::ControlTaskRequest> should match
// service_traits::DataType< ::car_interfaces::ControlTask >
template<>
struct DataType< ::car_interfaces::ControlTaskRequest>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::ControlTask >::value();
  }
  static const char* value(const ::car_interfaces::ControlTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_interfaces::ControlTaskResponse> should match
// service_traits::MD5Sum< ::car_interfaces::ControlTask >
template<>
struct MD5Sum< ::car_interfaces::ControlTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::ControlTask >::value();
  }
  static const char* value(const ::car_interfaces::ControlTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::ControlTaskResponse> should match
// service_traits::DataType< ::car_interfaces::ControlTask >
template<>
struct DataType< ::car_interfaces::ControlTaskResponse>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::ControlTask >::value();
  }
  static const char* value(const ::car_interfaces::ControlTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_CONTROLTASK_H
