// Generated by gencpp from file car_interfaces/ControlTaskRequest.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_CONTROLTASKREQUEST_H
#define CAR_INTERFACES_MESSAGE_CONTROLTASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_interfaces
{
template <class ContainerAllocator>
struct ControlTaskRequest_
{
  typedef ControlTaskRequest_<ContainerAllocator> Type;

  ControlTaskRequest_()
    : data(0)
    , limited_speed(0.0)  {
    }
  ControlTaskRequest_(const ContainerAllocator& _alloc)
    : data(0)
    , limited_speed(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _data_type;
  _data_type data;

   typedef float _limited_speed_type;
  _limited_speed_type limited_speed;





  typedef boost::shared_ptr< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControlTaskRequest_

typedef ::car_interfaces::ControlTaskRequest_<std::allocator<void> > ControlTaskRequest;

typedef boost::shared_ptr< ::car_interfaces::ControlTaskRequest > ControlTaskRequestPtr;
typedef boost::shared_ptr< ::car_interfaces::ControlTaskRequest const> ControlTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::ControlTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::ControlTaskRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::ControlTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.limited_speed == rhs.limited_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::ControlTaskRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::ControlTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3e034e54dd83ae8d69a3d23396e2610";
  }

  static const char* value(const ::car_interfaces::ControlTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3e034e54dd83ae8ULL;
  static const uint64_t static_value2 = 0xd69a3d23396e2610ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/ControlTaskRequest";
  }

  static const char* value(const ::car_interfaces::ControlTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 data\n"
"float32 limited_speed\n"
;
  }

  static const char* value(const ::car_interfaces::ControlTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.limited_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::ControlTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::ControlTaskRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "limited_speed: ";
    Printer<float>::stream(s, indent + "  ", v.limited_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_CONTROLTASKREQUEST_H
