// Generated by gencpp from file car_interfaces/Decision.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_DECISION_H
#define CAR_INTERFACES_MESSAGE_DECISION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_interfaces
{
template <class ContainerAllocator>
struct Decision_
{
  typedef Decision_<ContainerAllocator> Type;

  Decision_()
    : brake_enable(0.0)
    , value_brake(0.0)  {
    }
  Decision_(const ContainerAllocator& _alloc)
    : brake_enable(0.0)
    , value_brake(0.0)  {
  (void)_alloc;
    }



   typedef float _brake_enable_type;
  _brake_enable_type brake_enable;

   typedef float _value_brake_type;
  _value_brake_type value_brake;





  typedef boost::shared_ptr< ::car_interfaces::Decision_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::Decision_<ContainerAllocator> const> ConstPtr;

}; // struct Decision_

typedef ::car_interfaces::Decision_<std::allocator<void> > Decision;

typedef boost::shared_ptr< ::car_interfaces::Decision > DecisionPtr;
typedef boost::shared_ptr< ::car_interfaces::Decision const> DecisionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::Decision_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::Decision_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::Decision_<ContainerAllocator1> & lhs, const ::car_interfaces::Decision_<ContainerAllocator2> & rhs)
{
  return lhs.brake_enable == rhs.brake_enable &&
    lhs.value_brake == rhs.value_brake;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::Decision_<ContainerAllocator1> & lhs, const ::car_interfaces::Decision_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::Decision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::Decision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::Decision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::Decision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::Decision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::Decision_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::Decision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d400007abdee232a447063e2c6c629e0";
  }

  static const char* value(const ::car_interfaces::Decision_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd400007abdee232aULL;
  static const uint64_t static_value2 = 0x447063e2c6c629e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::Decision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/Decision";
  }

  static const char* value(const ::car_interfaces::Decision_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::Decision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 brake_enable  #刹车使能\n"
"float32 value_brake   #刹车量\n"
;
  }

  static const char* value(const ::car_interfaces::Decision_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::Decision_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.brake_enable);
      stream.next(m.value_brake);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Decision_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::Decision_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::Decision_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "brake_enable: ";
    Printer<float>::stream(s, indent + "  ", v.brake_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value_brake: ";
    Printer<float>::stream(s, indent + "  ", v.value_brake);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_DECISION_H
