// Generated by gencpp from file car_interfaces/EmergencyStopTask.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_EMERGENCYSTOPTASK_H
#define CAR_INTERFACES_MESSAGE_EMERGENCYSTOPTASK_H

#include <ros/service_traits.h>


#include <car_interfaces/EmergencyStopTaskRequest.h>
#include <car_interfaces/EmergencyStopTaskResponse.h>


namespace car_interfaces
{

struct EmergencyStopTask
{

typedef EmergencyStopTaskRequest Request;
typedef EmergencyStopTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EmergencyStopTask
} // namespace car_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_interfaces::EmergencyStopTask > {
  static const char* value()
  {
    return "208d4ab53cf12eb941a7d93b34b7532b";
  }

  static const char* value(const ::car_interfaces::EmergencyStopTask&) { return value(); }
};

template<>
struct DataType< ::car_interfaces::EmergencyStopTask > {
  static const char* value()
  {
    return "car_interfaces/EmergencyStopTask";
  }

  static const char* value(const ::car_interfaces::EmergencyStopTask&) { return value(); }
};


// service_traits::MD5Sum< ::car_interfaces::EmergencyStopTaskRequest> should match
// service_traits::MD5Sum< ::car_interfaces::EmergencyStopTask >
template<>
struct MD5Sum< ::car_interfaces::EmergencyStopTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::EmergencyStopTask >::value();
  }
  static const char* value(const ::car_interfaces::EmergencyStopTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::EmergencyStopTaskRequest> should match
// service_traits::DataType< ::car_interfaces::EmergencyStopTask >
template<>
struct DataType< ::car_interfaces::EmergencyStopTaskRequest>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::EmergencyStopTask >::value();
  }
  static const char* value(const ::car_interfaces::EmergencyStopTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_interfaces::EmergencyStopTaskResponse> should match
// service_traits::MD5Sum< ::car_interfaces::EmergencyStopTask >
template<>
struct MD5Sum< ::car_interfaces::EmergencyStopTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::EmergencyStopTask >::value();
  }
  static const char* value(const ::car_interfaces::EmergencyStopTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::EmergencyStopTaskResponse> should match
// service_traits::DataType< ::car_interfaces::EmergencyStopTask >
template<>
struct DataType< ::car_interfaces::EmergencyStopTaskResponse>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::EmergencyStopTask >::value();
  }
  static const char* value(const ::car_interfaces::EmergencyStopTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_EMERGENCYSTOPTASK_H
