// Generated by gencpp from file car_interfaces/FaultDiagnosisInterface.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_FAULTDIAGNOSISINTERFACE_H
#define CAR_INTERFACES_MESSAGE_FAULTDIAGNOSISINTERFACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_interfaces
{
template <class ContainerAllocator>
struct FaultDiagnosisInterface_
{
  typedef FaultDiagnosisInterface_<ContainerAllocator> Type;

  FaultDiagnosisInterface_()
    : lidar_state(0)
    , can_state(0)
    , gps_can_state(0)
    , gps_system_state(0)
    , camera_state(0)
    , internet_state(0)
    , v2n_state(0)
    , location_state(0)
    , sim_state(0)  {
    }
  FaultDiagnosisInterface_(const ContainerAllocator& _alloc)
    : lidar_state(0)
    , can_state(0)
    , gps_can_state(0)
    , gps_system_state(0)
    , camera_state(0)
    , internet_state(0)
    , v2n_state(0)
    , location_state(0)
    , sim_state(0)  {
  (void)_alloc;
    }



   typedef int8_t _lidar_state_type;
  _lidar_state_type lidar_state;

   typedef int8_t _can_state_type;
  _can_state_type can_state;

   typedef int8_t _gps_can_state_type;
  _gps_can_state_type gps_can_state;

   typedef int8_t _gps_system_state_type;
  _gps_system_state_type gps_system_state;

   typedef int8_t _camera_state_type;
  _camera_state_type camera_state;

   typedef int8_t _internet_state_type;
  _internet_state_type internet_state;

   typedef int8_t _v2n_state_type;
  _v2n_state_type v2n_state;

   typedef int8_t _location_state_type;
  _location_state_type location_state;

   typedef int8_t _sim_state_type;
  _sim_state_type sim_state;





  typedef boost::shared_ptr< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> const> ConstPtr;

}; // struct FaultDiagnosisInterface_

typedef ::car_interfaces::FaultDiagnosisInterface_<std::allocator<void> > FaultDiagnosisInterface;

typedef boost::shared_ptr< ::car_interfaces::FaultDiagnosisInterface > FaultDiagnosisInterfacePtr;
typedef boost::shared_ptr< ::car_interfaces::FaultDiagnosisInterface const> FaultDiagnosisInterfaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator2> & rhs)
{
  return lhs.lidar_state == rhs.lidar_state &&
    lhs.can_state == rhs.can_state &&
    lhs.gps_can_state == rhs.gps_can_state &&
    lhs.gps_system_state == rhs.gps_system_state &&
    lhs.camera_state == rhs.camera_state &&
    lhs.internet_state == rhs.internet_state &&
    lhs.v2n_state == rhs.v2n_state &&
    lhs.location_state == rhs.location_state &&
    lhs.sim_state == rhs.sim_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0acf205619b222615d838811655182ab";
  }

  static const char* value(const ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0acf205619b22261ULL;
  static const uint64_t static_value2 = 0x5d838811655182abULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/FaultDiagnosisInterface";
  }

  static const char* value(const ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 lidar_state\n"
"int8 can_state\n"
"int8 gps_can_state\n"
"int8 gps_system_state\n"
"int8 camera_state\n"
"int8 internet_state\n"
"\n"
"int8 v2n_state\n"
"int8 location_state\n"
"int8 sim_state\n"
;
  }

  static const char* value(const ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lidar_state);
      stream.next(m.can_state);
      stream.next(m.gps_can_state);
      stream.next(m.gps_system_state);
      stream.next(m.camera_state);
      stream.next(m.internet_state);
      stream.next(m.v2n_state);
      stream.next(m.location_state);
      stream.next(m.sim_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaultDiagnosisInterface_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::FaultDiagnosisInterface_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "lidar_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.lidar_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "can_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.can_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_can_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gps_can_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_system_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gps_system_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "camera_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.camera_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "internet_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.internet_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v2n_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.v2n_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "location_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.location_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sim_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sim_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_FAULTDIAGNOSISINTERFACE_H
