// Generated by gencpp from file car_interfaces/FusionDetTaskRequest.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_FUSIONDETTASKREQUEST_H
#define CAR_INTERFACES_MESSAGE_FUSIONDETTASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_interfaces
{
template <class ContainerAllocator>
struct FusionDetTaskRequest_
{
  typedef FusionDetTaskRequest_<ContainerAllocator> Type;

  FusionDetTaskRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , width(0.0)
    , height(0.0)
    , yaw(0.0)  {
    }
  FusionDetTaskRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , width(0.0)
    , height(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FusionDetTaskRequest_

typedef ::car_interfaces::FusionDetTaskRequest_<std::allocator<void> > FusionDetTaskRequest;

typedef boost::shared_ptr< ::car_interfaces::FusionDetTaskRequest > FusionDetTaskRequestPtr;
typedef boost::shared_ptr< ::car_interfaces::FusionDetTaskRequest const> FusionDetTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "314b95e462997d2f2a49e193f36c0671";
  }

  static const char* value(const ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x314b95e462997d2fULL;
  static const uint64_t static_value2 = 0x2a49e193f36c0671ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/FusionDetTaskRequest";
  }

  static const char* value(const ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# fusion_det_task\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 width\n"
"float32 height\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FusionDetTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::FusionDetTaskRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_FUSIONDETTASKREQUEST_H
