// Generated by gencpp from file car_interfaces/FusionDetTask.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_FUSIONDETTASK_H
#define CAR_INTERFACES_MESSAGE_FUSIONDETTASK_H

#include <ros/service_traits.h>


#include <car_interfaces/FusionDetTaskRequest.h>
#include <car_interfaces/FusionDetTaskResponse.h>


namespace car_interfaces
{

struct FusionDetTask
{

typedef FusionDetTaskRequest Request;
typedef FusionDetTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FusionDetTask
} // namespace car_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_interfaces::FusionDetTask > {
  static const char* value()
  {
    return "48cd9fb0e1c8c635b71f4ac18496bd3e";
  }

  static const char* value(const ::car_interfaces::FusionDetTask&) { return value(); }
};

template<>
struct DataType< ::car_interfaces::FusionDetTask > {
  static const char* value()
  {
    return "car_interfaces/FusionDetTask";
  }

  static const char* value(const ::car_interfaces::FusionDetTask&) { return value(); }
};


// service_traits::MD5Sum< ::car_interfaces::FusionDetTaskRequest> should match
// service_traits::MD5Sum< ::car_interfaces::FusionDetTask >
template<>
struct MD5Sum< ::car_interfaces::FusionDetTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::FusionDetTask >::value();
  }
  static const char* value(const ::car_interfaces::FusionDetTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::FusionDetTaskRequest> should match
// service_traits::DataType< ::car_interfaces::FusionDetTask >
template<>
struct DataType< ::car_interfaces::FusionDetTaskRequest>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::FusionDetTask >::value();
  }
  static const char* value(const ::car_interfaces::FusionDetTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_interfaces::FusionDetTaskResponse> should match
// service_traits::MD5Sum< ::car_interfaces::FusionDetTask >
template<>
struct MD5Sum< ::car_interfaces::FusionDetTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::FusionDetTask >::value();
  }
  static const char* value(const ::car_interfaces::FusionDetTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::FusionDetTaskResponse> should match
// service_traits::DataType< ::car_interfaces::FusionDetTask >
template<>
struct DataType< ::car_interfaces::FusionDetTaskResponse>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::FusionDetTask >::value();
  }
  static const char* value(const ::car_interfaces::FusionDetTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_FUSIONDETTASK_H
