// Generated by gencpp from file car_interfaces/GetInitPose.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_GETINITPOSE_H
#define CAR_INTERFACES_MESSAGE_GETINITPOSE_H

#include <ros/service_traits.h>


#include <car_interfaces/GetInitPoseRequest.h>
#include <car_interfaces/GetInitPoseResponse.h>


namespace car_interfaces
{

struct GetInitPose
{

typedef GetInitPoseRequest Request;
typedef GetInitPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInitPose
} // namespace car_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_interfaces::GetInitPose > {
  static const char* value()
  {
    return "8f01c405c2d32588f7064cc8b383fa9f";
  }

  static const char* value(const ::car_interfaces::GetInitPose&) { return value(); }
};

template<>
struct DataType< ::car_interfaces::GetInitPose > {
  static const char* value()
  {
    return "car_interfaces/GetInitPose";
  }

  static const char* value(const ::car_interfaces::GetInitPose&) { return value(); }
};


// service_traits::MD5Sum< ::car_interfaces::GetInitPoseRequest> should match
// service_traits::MD5Sum< ::car_interfaces::GetInitPose >
template<>
struct MD5Sum< ::car_interfaces::GetInitPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::GetInitPose >::value();
  }
  static const char* value(const ::car_interfaces::GetInitPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::GetInitPoseRequest> should match
// service_traits::DataType< ::car_interfaces::GetInitPose >
template<>
struct DataType< ::car_interfaces::GetInitPoseRequest>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::GetInitPose >::value();
  }
  static const char* value(const ::car_interfaces::GetInitPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_interfaces::GetInitPoseResponse> should match
// service_traits::MD5Sum< ::car_interfaces::GetInitPose >
template<>
struct MD5Sum< ::car_interfaces::GetInitPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::GetInitPose >::value();
  }
  static const char* value(const ::car_interfaces::GetInitPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::GetInitPoseResponse> should match
// service_traits::DataType< ::car_interfaces::GetInitPose >
template<>
struct DataType< ::car_interfaces::GetInitPoseResponse>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::GetInitPose >::value();
  }
  static const char* value(const ::car_interfaces::GetInitPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_GETINITPOSE_H
