// Generated by gencpp from file car_interfaces/GetInitPoseRequest.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_GETINITPOSEREQUEST_H
#define CAR_INTERFACES_MESSAGE_GETINITPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseWithCovarianceStamped.h>

namespace car_interfaces
{
template <class ContainerAllocator>
struct GetInitPoseRequest_
{
  typedef GetInitPoseRequest_<ContainerAllocator> Type;

  GetInitPoseRequest_()
    : init_pose()  {
    }
  GetInitPoseRequest_(const ContainerAllocator& _alloc)
    : init_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator>  _init_pose_type;
  _init_pose_type init_pose;





  typedef boost::shared_ptr< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetInitPoseRequest_

typedef ::car_interfaces::GetInitPoseRequest_<std::allocator<void> > GetInitPoseRequest;

typedef boost::shared_ptr< ::car_interfaces::GetInitPoseRequest > GetInitPoseRequestPtr;
typedef boost::shared_ptr< ::car_interfaces::GetInitPoseRequest const> GetInitPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::GetInitPoseRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::GetInitPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.init_pose == rhs.init_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::GetInitPoseRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::GetInitPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72a9f155bcbf3430934c9614710c8890";
  }

  static const char* value(const ::car_interfaces::GetInitPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72a9f155bcbf3430ULL;
  static const uint64_t static_value2 = 0x934c9614710c8890ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/GetInitPoseRequest";
  }

  static const char* value(const ::car_interfaces::GetInitPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 请求部分\n"
"geometry_msgs/PoseWithCovarianceStamped init_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovarianceStamped\n"
"# This expresses an estimated pose with a reference coordinate frame and timestamp\n"
"\n"
"Header header\n"
"PoseWithCovariance pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::car_interfaces::GetInitPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.init_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetInitPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::GetInitPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::GetInitPoseRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "init_pose: ";
    Printer< ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.init_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_GETINITPOSEREQUEST_H
