// Generated by gencpp from file car_interfaces/GetTargetPose.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_GETTARGETPOSE_H
#define CAR_INTERFACES_MESSAGE_GETTARGETPOSE_H

#include <ros/service_traits.h>


#include <car_interfaces/GetTargetPoseRequest.h>
#include <car_interfaces/GetTargetPoseResponse.h>


namespace car_interfaces
{

struct GetTargetPose
{

typedef GetTargetPoseRequest Request;
typedef GetTargetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTargetPose
} // namespace car_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_interfaces::GetTargetPose > {
  static const char* value()
  {
    return "4b25ad0cf04125d2d21d637138312288";
  }

  static const char* value(const ::car_interfaces::GetTargetPose&) { return value(); }
};

template<>
struct DataType< ::car_interfaces::GetTargetPose > {
  static const char* value()
  {
    return "car_interfaces/GetTargetPose";
  }

  static const char* value(const ::car_interfaces::GetTargetPose&) { return value(); }
};


// service_traits::MD5Sum< ::car_interfaces::GetTargetPoseRequest> should match
// service_traits::MD5Sum< ::car_interfaces::GetTargetPose >
template<>
struct MD5Sum< ::car_interfaces::GetTargetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::GetTargetPose >::value();
  }
  static const char* value(const ::car_interfaces::GetTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::GetTargetPoseRequest> should match
// service_traits::DataType< ::car_interfaces::GetTargetPose >
template<>
struct DataType< ::car_interfaces::GetTargetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::GetTargetPose >::value();
  }
  static const char* value(const ::car_interfaces::GetTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_interfaces::GetTargetPoseResponse> should match
// service_traits::MD5Sum< ::car_interfaces::GetTargetPose >
template<>
struct MD5Sum< ::car_interfaces::GetTargetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::GetTargetPose >::value();
  }
  static const char* value(const ::car_interfaces::GetTargetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::GetTargetPoseResponse> should match
// service_traits::DataType< ::car_interfaces::GetTargetPose >
template<>
struct DataType< ::car_interfaces::GetTargetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::GetTargetPose >::value();
  }
  static const char* value(const ::car_interfaces::GetTargetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_GETTARGETPOSE_H
