// Generated by gencpp from file car_interfaces/GetTargetPoseRequest.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_GETTARGETPOSEREQUEST_H
#define CAR_INTERFACES_MESSAGE_GETTARGETPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace car_interfaces
{
template <class ContainerAllocator>
struct GetTargetPoseRequest_
{
  typedef GetTargetPoseRequest_<ContainerAllocator> Type;

  GetTargetPoseRequest_()
    : tar_pose()  {
    }
  GetTargetPoseRequest_(const ContainerAllocator& _alloc)
    : tar_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _tar_pose_type;
  _tar_pose_type tar_pose;





  typedef boost::shared_ptr< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTargetPoseRequest_

typedef ::car_interfaces::GetTargetPoseRequest_<std::allocator<void> > GetTargetPoseRequest;

typedef boost::shared_ptr< ::car_interfaces::GetTargetPoseRequest > GetTargetPoseRequestPtr;
typedef boost::shared_ptr< ::car_interfaces::GetTargetPoseRequest const> GetTargetPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tar_pose == rhs.tar_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf1c04a981ffe8acd2385e130d1376f3";
  }

  static const char* value(const ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf1c04a981ffe8acULL;
  static const uint64_t static_value2 = 0xd2385e130d1376f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/GetTargetPoseRequest";
  }

  static const char* value(const ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped tar_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tar_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTargetPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::GetTargetPoseRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "tar_pose: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.tar_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_GETTARGETPOSEREQUEST_H
