// Generated by gencpp from file car_interfaces/GpsImuInterface.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_GPSIMUINTERFACE_H
#define CAR_INTERFACES_MESSAGE_GPSIMUINTERFACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace car_interfaces
{
template <class ContainerAllocator>
struct GpsImuInterface_
{
  typedef GpsImuInterface_<ContainerAllocator> Type;

  GpsImuInterface_()
    : nav_flag()
    , x_acc(0.0)
    , y_acc(0.0)
    , x_gyro(0.0)
    , y_gyro(0.0)
    , z_acc(0.0)
    , z_gyro(0.0)
    , acc(0.0)
    , gps_week(0.0)
    , gps_ms(0.0)
    , nav_flag_g()
    , header()
    , gps_time(0)
    , PosLon(0.0)
    , PosLat(0.0)
    , PosAlt(0.0)
    , lat_g(0.0)
    , lon_g(0.0)
    , east_speed_g(0.0)
    , north_speed_g(0.0)
    , up_speed_g(0.0)
    , alt_g(0.0)
    , heading_g(0.0)
    , VelE(0.0)
    , VelN(0.0)
    , VelU(0.0)
    , Vel(0.0)
    , AngleHeading(0.0)
    , AnglePitch(0.0)
    , AngleRoll(0.0)
    , system_state(0)
    , GpsNumSatsUsed(0)
    , satellite_status(0)
    , GpsAge(0.0)
    , state(false)
    , posX(0.0)
    , posY(0.0)
    , posZ(0.0)
    , process_time(0.0)
    , Gps_Cfault(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , pitch(0.0)
    , roll(0.0)
    , yaw(0.0)
    , vel(0.0)
    , lat(0.0)
    , lon(0.0)
    , state_ndt(false)  {
    }
  GpsImuInterface_(const ContainerAllocator& _alloc)
    : nav_flag(_alloc)
    , x_acc(0.0)
    , y_acc(0.0)
    , x_gyro(0.0)
    , y_gyro(0.0)
    , z_acc(0.0)
    , z_gyro(0.0)
    , acc(0.0)
    , gps_week(0.0)
    , gps_ms(0.0)
    , nav_flag_g(_alloc)
    , header(_alloc)
    , gps_time(0)
    , PosLon(0.0)
    , PosLat(0.0)
    , PosAlt(0.0)
    , lat_g(0.0)
    , lon_g(0.0)
    , east_speed_g(0.0)
    , north_speed_g(0.0)
    , up_speed_g(0.0)
    , alt_g(0.0)
    , heading_g(0.0)
    , VelE(0.0)
    , VelN(0.0)
    , VelU(0.0)
    , Vel(0.0)
    , AngleHeading(0.0)
    , AnglePitch(0.0)
    , AngleRoll(0.0)
    , system_state(0)
    , GpsNumSatsUsed(0)
    , satellite_status(0)
    , GpsAge(0.0)
    , state(false)
    , posX(0.0)
    , posY(0.0)
    , posZ(0.0)
    , process_time(0.0)
    , Gps_Cfault(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , pitch(0.0)
    , roll(0.0)
    , yaw(0.0)
    , vel(0.0)
    , lat(0.0)
    , lon(0.0)
    , state_ndt(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _nav_flag_type;
  _nav_flag_type nav_flag;

   typedef double _x_acc_type;
  _x_acc_type x_acc;

   typedef double _y_acc_type;
  _y_acc_type y_acc;

   typedef double _x_gyro_type;
  _x_gyro_type x_gyro;

   typedef double _y_gyro_type;
  _y_gyro_type y_gyro;

   typedef double _z_acc_type;
  _z_acc_type z_acc;

   typedef double _z_gyro_type;
  _z_gyro_type z_gyro;

   typedef double _acc_type;
  _acc_type acc;

   typedef double _gps_week_type;
  _gps_week_type gps_week;

   typedef double _gps_ms_type;
  _gps_ms_type gps_ms;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _nav_flag_g_type;
  _nav_flag_g_type nav_flag_g;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _gps_time_type;
  _gps_time_type gps_time;

   typedef double _PosLon_type;
  _PosLon_type PosLon;

   typedef double _PosLat_type;
  _PosLat_type PosLat;

   typedef double _PosAlt_type;
  _PosAlt_type PosAlt;

   typedef double _lat_g_type;
  _lat_g_type lat_g;

   typedef double _lon_g_type;
  _lon_g_type lon_g;

   typedef double _east_speed_g_type;
  _east_speed_g_type east_speed_g;

   typedef double _north_speed_g_type;
  _north_speed_g_type north_speed_g;

   typedef double _up_speed_g_type;
  _up_speed_g_type up_speed_g;

   typedef double _alt_g_type;
  _alt_g_type alt_g;

   typedef double _heading_g_type;
  _heading_g_type heading_g;

   typedef double _VelE_type;
  _VelE_type VelE;

   typedef double _VelN_type;
  _VelN_type VelN;

   typedef double _VelU_type;
  _VelU_type VelU;

   typedef double _Vel_type;
  _Vel_type Vel;

   typedef double _AngleHeading_type;
  _AngleHeading_type AngleHeading;

   typedef double _AnglePitch_type;
  _AnglePitch_type AnglePitch;

   typedef double _AngleRoll_type;
  _AngleRoll_type AngleRoll;

   typedef int32_t _system_state_type;
  _system_state_type system_state;

   typedef int32_t _GpsNumSatsUsed_type;
  _GpsNumSatsUsed_type GpsNumSatsUsed;

   typedef int32_t _satellite_status_type;
  _satellite_status_type satellite_status;

   typedef double _GpsAge_type;
  _GpsAge_type GpsAge;

   typedef uint8_t _state_type;
  _state_type state;

   typedef double _posX_type;
  _posX_type posX;

   typedef double _posY_type;
  _posY_type posY;

   typedef double _posZ_type;
  _posZ_type posZ;

   typedef double _process_time_type;
  _process_time_type process_time;

   typedef uint8_t _Gps_Cfault_type;
  _Gps_Cfault_type Gps_Cfault;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _vel_type;
  _vel_type vel;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef uint8_t _state_ndt_type;
  _state_ndt_type state_ndt;





  typedef boost::shared_ptr< ::car_interfaces::GpsImuInterface_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::GpsImuInterface_<ContainerAllocator> const> ConstPtr;

}; // struct GpsImuInterface_

typedef ::car_interfaces::GpsImuInterface_<std::allocator<void> > GpsImuInterface;

typedef boost::shared_ptr< ::car_interfaces::GpsImuInterface > GpsImuInterfacePtr;
typedef boost::shared_ptr< ::car_interfaces::GpsImuInterface const> GpsImuInterfaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::GpsImuInterface_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::GpsImuInterface_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::GpsImuInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::GpsImuInterface_<ContainerAllocator2> & rhs)
{
  return lhs.nav_flag == rhs.nav_flag &&
    lhs.x_acc == rhs.x_acc &&
    lhs.y_acc == rhs.y_acc &&
    lhs.x_gyro == rhs.x_gyro &&
    lhs.y_gyro == rhs.y_gyro &&
    lhs.z_acc == rhs.z_acc &&
    lhs.z_gyro == rhs.z_gyro &&
    lhs.acc == rhs.acc &&
    lhs.gps_week == rhs.gps_week &&
    lhs.gps_ms == rhs.gps_ms &&
    lhs.nav_flag_g == rhs.nav_flag_g &&
    lhs.header == rhs.header &&
    lhs.gps_time == rhs.gps_time &&
    lhs.PosLon == rhs.PosLon &&
    lhs.PosLat == rhs.PosLat &&
    lhs.PosAlt == rhs.PosAlt &&
    lhs.lat_g == rhs.lat_g &&
    lhs.lon_g == rhs.lon_g &&
    lhs.east_speed_g == rhs.east_speed_g &&
    lhs.north_speed_g == rhs.north_speed_g &&
    lhs.up_speed_g == rhs.up_speed_g &&
    lhs.alt_g == rhs.alt_g &&
    lhs.heading_g == rhs.heading_g &&
    lhs.VelE == rhs.VelE &&
    lhs.VelN == rhs.VelN &&
    lhs.VelU == rhs.VelU &&
    lhs.Vel == rhs.Vel &&
    lhs.AngleHeading == rhs.AngleHeading &&
    lhs.AnglePitch == rhs.AnglePitch &&
    lhs.AngleRoll == rhs.AngleRoll &&
    lhs.system_state == rhs.system_state &&
    lhs.GpsNumSatsUsed == rhs.GpsNumSatsUsed &&
    lhs.satellite_status == rhs.satellite_status &&
    lhs.GpsAge == rhs.GpsAge &&
    lhs.state == rhs.state &&
    lhs.posX == rhs.posX &&
    lhs.posY == rhs.posY &&
    lhs.posZ == rhs.posZ &&
    lhs.process_time == rhs.process_time &&
    lhs.Gps_Cfault == rhs.Gps_Cfault &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll &&
    lhs.yaw == rhs.yaw &&
    lhs.vel == rhs.vel &&
    lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon &&
    lhs.state_ndt == rhs.state_ndt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::GpsImuInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::GpsImuInterface_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::GpsImuInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::GpsImuInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::GpsImuInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::GpsImuInterface_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::GpsImuInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::GpsImuInterface_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::GpsImuInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9bc67efa4f7a3a9f25eb10a367521b4";
  }

  static const char* value(const ::car_interfaces::GpsImuInterface_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9bc67efa4f7a3a9ULL;
  static const uint64_t static_value2 = 0xf25eb10a367521b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::GpsImuInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/GpsImuInterface";
  }

  static const char* value(const ::car_interfaces::GpsImuInterface_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::GpsImuInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string nav_flag #定位无效-0  单点解-1  差分定位-2  RTK固定解-4  RTK浮点解-5 递推-6\n"
"\n"
"float64 x_acc\n"
"float64 y_acc\n"
"float64 x_gyro\n"
"float64 y_gyro\n"
"float64 z_acc\n"
"float64 z_gyro\n"
"\n"
"float64 acc\n"
"float64 gps_week\n"
"float64 gps_ms\n"
"\n"
"string nav_flag_g #无效解	0\n"
"# #单点解	1\n"
"# #差分解	2\n"
"# #浮点解	5\n"
"# #窄固定解（narrow int）	4\n"
"# #其它固定解	7\n"
"# #ID:0X51B gnss航向\n"
"# float32 heading_g\n"
"\n"
"std_msgs/Header header       # ros时间戳\n"
"int64  gps_time              #时间戳\n"
"\n"
"float64  PosLon        # 经度\n"
"float64  PosLat         # 纬度\n"
"float64  PosAlt         # 高度\n"
"\n"
"float64 lat_g\n"
"float64 lon_g\n"
"\n"
"float64 east_speed_g\n"
"float64 north_speed_g\n"
"float64 up_speed_g\n"
"float64 alt_g\n"
"float64 heading_g\n"
"\n"
"float64  VelE         # 东向速度\n"
"float64  VelN        # 北向速度\n"
"float64  VelU        # 天向速度\n"
"float64  Vel          # 车辆速度\n"
"\n"
"float64  AngleHeading         # 偏航角（-180-180）  #需要这个范围\n"
"float64  AnglePitch        # 俯仰角（-90-90）\n"
"float64  AngleRoll         # 横滚角（-180-180）\n"
"\n"
"int32  system_state                #惯导模式（0-初始化；1-卫导模式；2-组合导航模式；3-纯惯导模式）\n"
"int32  GpsNumSatsUsed         #主天线使用卫星数\n"
"int32  satellite_status              #卫星状态（0-不定位不定向；1-单点定位定向；   2-伪距差分定位定向；3-组合推算；4-RTK稳定解定位定向；5-RTK浮点解定位定向；6-单点定位不定向； 7-伪距差分定位不定向；8-RTK稳定解定位不定向；9-RTK浮点解定位不定向）\n"
"float64  GpsAge                     #差分延时\n"
"bool  state                      #设备状态（0-状态异常；1-状态正常）\n"
"float64 posX                    #定位点UTM坐标x\n"
"float64 posY                    #定位点UTM坐标y\n"
"float64 posZ # 高程\n"
"float64  process_time        #进程处理时间\n"
"bool Gps_Cfault  #惯导通信故障\n"
"\n"
"# 带slam的相应的数据：\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 pitch\n"
"float64 roll\n"
"float64 yaw\n"
"float64 vel\n"
"float64 lat\n"
"float64 lon\n"
"bool state_ndt\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::car_interfaces::GpsImuInterface_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::GpsImuInterface_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nav_flag);
      stream.next(m.x_acc);
      stream.next(m.y_acc);
      stream.next(m.x_gyro);
      stream.next(m.y_gyro);
      stream.next(m.z_acc);
      stream.next(m.z_gyro);
      stream.next(m.acc);
      stream.next(m.gps_week);
      stream.next(m.gps_ms);
      stream.next(m.nav_flag_g);
      stream.next(m.header);
      stream.next(m.gps_time);
      stream.next(m.PosLon);
      stream.next(m.PosLat);
      stream.next(m.PosAlt);
      stream.next(m.lat_g);
      stream.next(m.lon_g);
      stream.next(m.east_speed_g);
      stream.next(m.north_speed_g);
      stream.next(m.up_speed_g);
      stream.next(m.alt_g);
      stream.next(m.heading_g);
      stream.next(m.VelE);
      stream.next(m.VelN);
      stream.next(m.VelU);
      stream.next(m.Vel);
      stream.next(m.AngleHeading);
      stream.next(m.AnglePitch);
      stream.next(m.AngleRoll);
      stream.next(m.system_state);
      stream.next(m.GpsNumSatsUsed);
      stream.next(m.satellite_status);
      stream.next(m.GpsAge);
      stream.next(m.state);
      stream.next(m.posX);
      stream.next(m.posY);
      stream.next(m.posZ);
      stream.next(m.process_time);
      stream.next(m.Gps_Cfault);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.yaw);
      stream.next(m.vel);
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.state_ndt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsImuInterface_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::GpsImuInterface_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::GpsImuInterface_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "nav_flag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.nav_flag);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_acc: ";
    Printer<double>::stream(s, indent + "  ", v.x_acc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_acc: ";
    Printer<double>::stream(s, indent + "  ", v.y_acc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_gyro: ";
    Printer<double>::stream(s, indent + "  ", v.x_gyro);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_gyro: ";
    Printer<double>::stream(s, indent + "  ", v.y_gyro);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z_acc: ";
    Printer<double>::stream(s, indent + "  ", v.z_acc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z_gyro: ";
    Printer<double>::stream(s, indent + "  ", v.z_gyro);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc: ";
    Printer<double>::stream(s, indent + "  ", v.acc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_week: ";
    Printer<double>::stream(s, indent + "  ", v.gps_week);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_ms: ";
    Printer<double>::stream(s, indent + "  ", v.gps_ms);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "nav_flag_g: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.nav_flag_g);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_time: ";
    Printer<int64_t>::stream(s, indent + "  ", v.gps_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "PosLon: ";
    Printer<double>::stream(s, indent + "  ", v.PosLon);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "PosLat: ";
    Printer<double>::stream(s, indent + "  ", v.PosLat);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "PosAlt: ";
    Printer<double>::stream(s, indent + "  ", v.PosAlt);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lat_g: ";
    Printer<double>::stream(s, indent + "  ", v.lat_g);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lon_g: ";
    Printer<double>::stream(s, indent + "  ", v.lon_g);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "east_speed_g: ";
    Printer<double>::stream(s, indent + "  ", v.east_speed_g);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "north_speed_g: ";
    Printer<double>::stream(s, indent + "  ", v.north_speed_g);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "up_speed_g: ";
    Printer<double>::stream(s, indent + "  ", v.up_speed_g);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "alt_g: ";
    Printer<double>::stream(s, indent + "  ", v.alt_g);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "heading_g: ";
    Printer<double>::stream(s, indent + "  ", v.heading_g);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "VelE: ";
    Printer<double>::stream(s, indent + "  ", v.VelE);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "VelN: ";
    Printer<double>::stream(s, indent + "  ", v.VelN);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "VelU: ";
    Printer<double>::stream(s, indent + "  ", v.VelU);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Vel: ";
    Printer<double>::stream(s, indent + "  ", v.Vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "AngleHeading: ";
    Printer<double>::stream(s, indent + "  ", v.AngleHeading);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "AnglePitch: ";
    Printer<double>::stream(s, indent + "  ", v.AnglePitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "AngleRoll: ";
    Printer<double>::stream(s, indent + "  ", v.AngleRoll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "system_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.system_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "GpsNumSatsUsed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.GpsNumSatsUsed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "satellite_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.satellite_status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "GpsAge: ";
    Printer<double>::stream(s, indent + "  ", v.GpsAge);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "posX: ";
    Printer<double>::stream(s, indent + "  ", v.posX);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "posY: ";
    Printer<double>::stream(s, indent + "  ", v.posY);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "posZ: ";
    Printer<double>::stream(s, indent + "  ", v.posZ);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "process_time: ";
    Printer<double>::stream(s, indent + "  ", v.process_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Gps_Cfault: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Gps_Cfault);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel: ";
    Printer<double>::stream(s, indent + "  ", v.vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state_ndt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state_ndt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_GPSIMUINTERFACE_H
