// Generated by gencpp from file car_interfaces/Object.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_OBJECT_H
#define CAR_INTERFACES_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_interfaces
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : conf(0.0)
    , class_id(0.0)
    , track_id(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , l_x(0.0)
    , l_y(0.0)
    , l_z(0.0)
    , pitch(0.0)
    , roll(0.0)
    , yaw(0.0)
    , degree(0.0)
    , distance(0.0)
    , height(0.0)
    , target_width(0.0)
    , target_height(0.0)
    , left_boudary_point()
    , right_boudary_point()
    , top_boudary_point()  {
    }
  Object_(const ContainerAllocator& _alloc)
    : conf(0.0)
    , class_id(0.0)
    , track_id(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , l_x(0.0)
    , l_y(0.0)
    , l_z(0.0)
    , pitch(0.0)
    , roll(0.0)
    , yaw(0.0)
    , degree(0.0)
    , distance(0.0)
    , height(0.0)
    , target_width(0.0)
    , target_height(0.0)
    , left_boudary_point(_alloc)
    , right_boudary_point(_alloc)
    , top_boudary_point(_alloc)  {
  (void)_alloc;
    }



   typedef float _conf_type;
  _conf_type conf;

   typedef float _class_id_type;
  _class_id_type class_id;

   typedef float _track_id_type;
  _track_id_type track_id;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _l_x_type;
  _l_x_type l_x;

   typedef float _l_y_type;
  _l_y_type l_y;

   typedef float _l_z_type;
  _l_z_type l_z;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _degree_type;
  _degree_type degree;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _height_type;
  _height_type height;

   typedef float _target_width_type;
  _target_width_type target_width;

   typedef float _target_height_type;
  _target_height_type target_height;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _left_boudary_point_type;
  _left_boudary_point_type left_boudary_point;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _right_boudary_point_type;
  _right_boudary_point_type right_boudary_point;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _top_boudary_point_type;
  _top_boudary_point_type top_boudary_point;





  typedef boost::shared_ptr< ::car_interfaces::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::car_interfaces::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::car_interfaces::Object > ObjectPtr;
typedef boost::shared_ptr< ::car_interfaces::Object const> ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::Object_<ContainerAllocator1> & lhs, const ::car_interfaces::Object_<ContainerAllocator2> & rhs)
{
  return lhs.conf == rhs.conf &&
    lhs.class_id == rhs.class_id &&
    lhs.track_id == rhs.track_id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.l_x == rhs.l_x &&
    lhs.l_y == rhs.l_y &&
    lhs.l_z == rhs.l_z &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll &&
    lhs.yaw == rhs.yaw &&
    lhs.degree == rhs.degree &&
    lhs.distance == rhs.distance &&
    lhs.height == rhs.height &&
    lhs.target_width == rhs.target_width &&
    lhs.target_height == rhs.target_height &&
    lhs.left_boudary_point == rhs.left_boudary_point &&
    lhs.right_boudary_point == rhs.right_boudary_point &&
    lhs.top_boudary_point == rhs.top_boudary_point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::Object_<ContainerAllocator1> & lhs, const ::car_interfaces::Object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::Object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "693ea0c1d42830af046c93ddc187f2b2";
  }

  static const char* value(const ::car_interfaces::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x693ea0c1d42830afULL;
  static const uint64_t static_value2 = 0x046c93ddc187f2b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/Object";
  }

  static const char* value(const ::car_interfaces::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 conf            # 得分\n"
"float32 class_id        # 类别\n"
"float32 track_id	    # 跟踪id\n"
"float32 x               # 全局 相对加+车辆定位  单位m\n"
"float32 y	            # 全局 相对加+车辆定位  单位m\n"
"float32 z	            # 全局 相对加+车辆定位  单位m\n"
"float32 l_x	            # 相对 单位m\n"
"float32 l_y	            # 相对 单位m\n"
"float32 l_z	            # 相对 单位m\n"
"float32 pitch	        # unit:rad,关于车辆坐标系z轴角度+车辆pitch \n"
"float32 roll	        # unit:rad,关于车辆坐标系y轴角度+车辆roll \n"
"float32 yaw	            # unit:rad,degree+车辆航向 yaw \n"
"float32 degree	        # 角度,车辆坐标系x轴夹角 \n"
"float32 distance	    # 单位m\n"
"float32 height	        # 单位m\n"
"float32 target_width    # 单位m\n"
"float32 target_height   # 单位m\n"
"float32[] left_boudary_point\n"
"float32[] right_boudary_point\n"
"float32[] top_boudary_point\n"
;
  }

  static const char* value(const ::car_interfaces::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.conf);
      stream.next(m.class_id);
      stream.next(m.track_id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.l_x);
      stream.next(m.l_y);
      stream.next(m.l_z);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.yaw);
      stream.next(m.degree);
      stream.next(m.distance);
      stream.next(m.height);
      stream.next(m.target_width);
      stream.next(m.target_height);
      stream.next(m.left_boudary_point);
      stream.next(m.right_boudary_point);
      stream.next(m.top_boudary_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::Object_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "conf: ";
    Printer<float>::stream(s, indent + "  ", v.conf);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "class_id: ";
    Printer<float>::stream(s, indent + "  ", v.class_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "track_id: ";
    Printer<float>::stream(s, indent + "  ", v.track_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "l_x: ";
    Printer<float>::stream(s, indent + "  ", v.l_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "l_y: ";
    Printer<float>::stream(s, indent + "  ", v.l_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "l_z: ";
    Printer<float>::stream(s, indent + "  ", v.l_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "degree: ";
    Printer<float>::stream(s, indent + "  ", v.degree);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_width: ";
    Printer<float>::stream(s, indent + "  ", v.target_width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_height: ";
    Printer<float>::stream(s, indent + "  ", v.target_height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_boudary_point: ";
    if (v.left_boudary_point.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.left_boudary_point.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.left_boudary_point[i]);
    }
    if (v.left_boudary_point.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_boudary_point: ";
    if (v.right_boudary_point.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.right_boudary_point.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.right_boudary_point[i]);
    }
    if (v.right_boudary_point.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "top_boudary_point: ";
    if (v.top_boudary_point.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.top_boudary_point.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.top_boudary_point[i]);
    }
    if (v.top_boudary_point.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_OBJECT_H
