// Generated by gencpp from file car_interfaces/PalletInterface.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_PALLETINTERFACE_H
#define CAR_INTERFACES_MESSAGE_PALLETINTERFACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_interfaces
{
template <class ContainerAllocator>
struct PalletInterface_
{
  typedef PalletInterface_<ContainerAllocator> Type;

  PalletInterface_()
    : pallet_x(0.0)
    , pallet_y(0.0)
    , pallet_heading(0.0)  {
    }
  PalletInterface_(const ContainerAllocator& _alloc)
    : pallet_x(0.0)
    , pallet_y(0.0)
    , pallet_heading(0.0)  {
  (void)_alloc;
    }



   typedef double _pallet_x_type;
  _pallet_x_type pallet_x;

   typedef double _pallet_y_type;
  _pallet_y_type pallet_y;

   typedef double _pallet_heading_type;
  _pallet_heading_type pallet_heading;





  typedef boost::shared_ptr< ::car_interfaces::PalletInterface_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::PalletInterface_<ContainerAllocator> const> ConstPtr;

}; // struct PalletInterface_

typedef ::car_interfaces::PalletInterface_<std::allocator<void> > PalletInterface;

typedef boost::shared_ptr< ::car_interfaces::PalletInterface > PalletInterfacePtr;
typedef boost::shared_ptr< ::car_interfaces::PalletInterface const> PalletInterfaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::PalletInterface_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::PalletInterface_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::PalletInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::PalletInterface_<ContainerAllocator2> & rhs)
{
  return lhs.pallet_x == rhs.pallet_x &&
    lhs.pallet_y == rhs.pallet_y &&
    lhs.pallet_heading == rhs.pallet_heading;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::PalletInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::PalletInterface_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::PalletInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::PalletInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::PalletInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::PalletInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::PalletInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::PalletInterface_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::PalletInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3851b4afec05d2d716993bd4b1f4057";
  }

  static const char* value(const ::car_interfaces::PalletInterface_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3851b4afec05d2dULL;
  static const uint64_t static_value2 = 0x716993bd4b1f4057ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::PalletInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/PalletInterface";
  }

  static const char* value(const ::car_interfaces::PalletInterface_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::PalletInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pallet_x\n"
"float64 pallet_y\n"
"\n"
"float64 pallet_heading\n"
;
  }

  static const char* value(const ::car_interfaces::PalletInterface_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::PalletInterface_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pallet_x);
      stream.next(m.pallet_y);
      stream.next(m.pallet_heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PalletInterface_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::PalletInterface_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::PalletInterface_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pallet_x: ";
    Printer<double>::stream(s, indent + "  ", v.pallet_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pallet_y: ";
    Printer<double>::stream(s, indent + "  ", v.pallet_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pallet_heading: ";
    Printer<double>::stream(s, indent + "  ", v.pallet_heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_PALLETINTERFACE_H
