// Generated by gencpp from file car_interfaces/Pathplan.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_PATHPLAN_H
#define CAR_INTERFACES_MESSAGE_PATHPLAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <car_interfaces/Pointplan.h>

namespace car_interfaces
{
template <class ContainerAllocator>
struct Pathplan_
{
  typedef Pathplan_<ContainerAllocator> Type;

  Pathplan_()
    : points()  {
    }
  Pathplan_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::car_interfaces::Pointplan_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::car_interfaces::Pointplan_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::car_interfaces::Pathplan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::Pathplan_<ContainerAllocator> const> ConstPtr;

}; // struct Pathplan_

typedef ::car_interfaces::Pathplan_<std::allocator<void> > Pathplan;

typedef boost::shared_ptr< ::car_interfaces::Pathplan > PathplanPtr;
typedef boost::shared_ptr< ::car_interfaces::Pathplan const> PathplanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::Pathplan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::Pathplan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::Pathplan_<ContainerAllocator1> & lhs, const ::car_interfaces::Pathplan_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::Pathplan_<ContainerAllocator1> & lhs, const ::car_interfaces::Pathplan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::Pathplan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::Pathplan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::Pathplan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::Pathplan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::Pathplan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::Pathplan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::Pathplan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c4c89b7b017e468ad8dfddbec0bf5e6";
  }

  static const char* value(const ::car_interfaces::Pathplan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c4c89b7b017e468ULL;
  static const uint64_t static_value2 = 0xad8dfddbec0bf5e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::Pathplan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/Pathplan";
  }

  static const char* value(const ::car_interfaces::Pathplan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::Pathplan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Pointplan[] points\n"
"================================================================================\n"
"MSG: car_interfaces/Pointplan\n"
"float64 x\n"
"float64 y\n"
"float64 yaw\n"
"float64 speed\n"
"float64 kappa\n"
"int8 gear\n"
"\n"
;
  }

  static const char* value(const ::car_interfaces::Pathplan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::Pathplan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pathplan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::Pathplan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::Pathplan_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "points: ";
    if (v.points.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::car_interfaces::Pointplan_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.points[i]);
    }
    if (v.points.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_PATHPLAN_H
