// Generated by gencpp from file car_interfaces/PathGlobal.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_PATHGLOBAL_H
#define CAR_INTERFACES_MESSAGE_PATHGLOBAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace car_interfaces
{
template <class ContainerAllocator>
struct PathGlobal_
{
  typedef PathGlobal_<ContainerAllocator> Type;

  PathGlobal_()
    : timestamp(0.0)
    , startpoint()
    , goal_received(false)
    , path()  {
    }
  PathGlobal_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , startpoint(_alloc)
    , goal_received(false)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _startpoint_type;
  _startpoint_type startpoint;

   typedef uint8_t _goal_received_type;
  _goal_received_type goal_received;

   typedef  ::nav_msgs::Path_<ContainerAllocator>  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::car_interfaces::PathGlobal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::PathGlobal_<ContainerAllocator> const> ConstPtr;

}; // struct PathGlobal_

typedef ::car_interfaces::PathGlobal_<std::allocator<void> > PathGlobal;

typedef boost::shared_ptr< ::car_interfaces::PathGlobal > PathGlobalPtr;
typedef boost::shared_ptr< ::car_interfaces::PathGlobal const> PathGlobalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::PathGlobal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::PathGlobal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::PathGlobal_<ContainerAllocator1> & lhs, const ::car_interfaces::PathGlobal_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.startpoint == rhs.startpoint &&
    lhs.goal_received == rhs.goal_received &&
    lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::PathGlobal_<ContainerAllocator1> & lhs, const ::car_interfaces::PathGlobal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::PathGlobal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::PathGlobal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::PathGlobal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::PathGlobal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::PathGlobal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::PathGlobal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::PathGlobal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b37aa2b40541c58a99e5b6f91bb685b0";
  }

  static const char* value(const ::car_interfaces::PathGlobal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb37aa2b40541c58aULL;
  static const uint64_t static_value2 = 0x99e5b6f91bb685b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::PathGlobal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/PathGlobal";
  }

  static const char* value(const ::car_interfaces::PathGlobal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::PathGlobal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64  timestamp  #时间戳\n"
"float64[]  startpoint   #起点位置\n"
"bool goal_received\n"
"nav_msgs/Path path\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::car_interfaces::PathGlobal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::PathGlobal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.startpoint);
      stream.next(m.goal_received);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathGlobal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::PathGlobal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::PathGlobal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "startpoint: ";
    if (v.startpoint.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.startpoint.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.startpoint[i]);
    }
    if (v.startpoint.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goal_received);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "path: ";
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_PATHGLOBAL_H
