// Generated by gencpp from file car_interfaces/PlanTask.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_PLANTASK_H
#define CAR_INTERFACES_MESSAGE_PLANTASK_H

#include <ros/service_traits.h>


#include <car_interfaces/PlanTaskRequest.h>
#include <car_interfaces/PlanTaskResponse.h>


namespace car_interfaces
{

struct PlanTask
{

typedef PlanTaskRequest Request;
typedef PlanTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanTask
} // namespace car_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_interfaces::PlanTask > {
  static const char* value()
  {
    return "208d4ab53cf12eb941a7d93b34b7532b";
  }

  static const char* value(const ::car_interfaces::PlanTask&) { return value(); }
};

template<>
struct DataType< ::car_interfaces::PlanTask > {
  static const char* value()
  {
    return "car_interfaces/PlanTask";
  }

  static const char* value(const ::car_interfaces::PlanTask&) { return value(); }
};


// service_traits::MD5Sum< ::car_interfaces::PlanTaskRequest> should match
// service_traits::MD5Sum< ::car_interfaces::PlanTask >
template<>
struct MD5Sum< ::car_interfaces::PlanTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::PlanTask >::value();
  }
  static const char* value(const ::car_interfaces::PlanTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::PlanTaskRequest> should match
// service_traits::DataType< ::car_interfaces::PlanTask >
template<>
struct DataType< ::car_interfaces::PlanTaskRequest>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::PlanTask >::value();
  }
  static const char* value(const ::car_interfaces::PlanTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_interfaces::PlanTaskResponse> should match
// service_traits::MD5Sum< ::car_interfaces::PlanTask >
template<>
struct MD5Sum< ::car_interfaces::PlanTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::PlanTask >::value();
  }
  static const char* value(const ::car_interfaces::PlanTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::PlanTaskResponse> should match
// service_traits::DataType< ::car_interfaces::PlanTask >
template<>
struct DataType< ::car_interfaces::PlanTaskResponse>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::PlanTask >::value();
  }
  static const char* value(const ::car_interfaces::PlanTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_PLANTASK_H
