// Generated by gencpp from file car_interfaces/PlanTaskRequest.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_PLANTASKREQUEST_H
#define CAR_INTERFACES_MESSAGE_PLANTASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_interfaces
{
template <class ContainerAllocator>
struct PlanTaskRequest_
{
  typedef PlanTaskRequest_<ContainerAllocator> Type;

  PlanTaskRequest_()
    : data(0)  {
    }
  PlanTaskRequest_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlanTaskRequest_

typedef ::car_interfaces::PlanTaskRequest_<std::allocator<void> > PlanTaskRequest;

typedef boost::shared_ptr< ::car_interfaces::PlanTaskRequest > PlanTaskRequestPtr;
typedef boost::shared_ptr< ::car_interfaces::PlanTaskRequest const> PlanTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::PlanTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::PlanTaskRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::PlanTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::PlanTaskRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::PlanTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27ffa0c9c4b8fb8492252bcad9e5c57b";
  }

  static const char* value(const ::car_interfaces::PlanTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27ffa0c9c4b8fb84ULL;
  static const uint64_t static_value2 = 0x92252bcad9e5c57bULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/PlanTaskRequest";
  }

  static const char* value(const ::car_interfaces::PlanTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 data\n"
;
  }

  static const char* value(const ::car_interfaces::PlanTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::PlanTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::PlanTaskRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_PLANTASKREQUEST_H
