// Generated by gencpp from file car_interfaces/Pointplan.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_POINTPLAN_H
#define CAR_INTERFACES_MESSAGE_POINTPLAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_interfaces
{
template <class ContainerAllocator>
struct Pointplan_
{
  typedef Pointplan_<ContainerAllocator> Type;

  Pointplan_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , speed(0.0)
    , kappa(0.0)
    , gear(0)  {
    }
  Pointplan_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , speed(0.0)
    , kappa(0.0)
    , gear(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _speed_type;
  _speed_type speed;

   typedef double _kappa_type;
  _kappa_type kappa;

   typedef int8_t _gear_type;
  _gear_type gear;





  typedef boost::shared_ptr< ::car_interfaces::Pointplan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::Pointplan_<ContainerAllocator> const> ConstPtr;

}; // struct Pointplan_

typedef ::car_interfaces::Pointplan_<std::allocator<void> > Pointplan;

typedef boost::shared_ptr< ::car_interfaces::Pointplan > PointplanPtr;
typedef boost::shared_ptr< ::car_interfaces::Pointplan const> PointplanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::Pointplan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::Pointplan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::Pointplan_<ContainerAllocator1> & lhs, const ::car_interfaces::Pointplan_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw &&
    lhs.speed == rhs.speed &&
    lhs.kappa == rhs.kappa &&
    lhs.gear == rhs.gear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::Pointplan_<ContainerAllocator1> & lhs, const ::car_interfaces::Pointplan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::Pointplan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::Pointplan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::Pointplan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::Pointplan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::Pointplan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::Pointplan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::Pointplan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "850c063414ceef1c3a3866beea2ae24e";
  }

  static const char* value(const ::car_interfaces::Pointplan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x850c063414ceef1cULL;
  static const uint64_t static_value2 = 0x3a3866beea2ae24eULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::Pointplan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/Pointplan";
  }

  static const char* value(const ::car_interfaces::Pointplan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::Pointplan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 yaw\n"
"float64 speed\n"
"float64 kappa\n"
"int8 gear\n"
"\n"
;
  }

  static const char* value(const ::car_interfaces::Pointplan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::Pointplan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
      stream.next(m.speed);
      stream.next(m.kappa);
      stream.next(m.gear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pointplan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::Pointplan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::Pointplan_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "kappa: ";
    Printer<double>::stream(s, indent + "  ", v.kappa);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gear: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_POINTPLAN_H
