// Generated by gencpp from file car_interfaces/PositionTask.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_POSITIONTASK_H
#define CAR_INTERFACES_MESSAGE_POSITIONTASK_H

#include <ros/service_traits.h>


#include <car_interfaces/PositionTaskRequest.h>
#include <car_interfaces/PositionTaskResponse.h>


namespace car_interfaces
{

struct PositionTask
{

typedef PositionTaskRequest Request;
typedef PositionTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PositionTask
} // namespace car_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_interfaces::PositionTask > {
  static const char* value()
  {
    return "208d4ab53cf12eb941a7d93b34b7532b";
  }

  static const char* value(const ::car_interfaces::PositionTask&) { return value(); }
};

template<>
struct DataType< ::car_interfaces::PositionTask > {
  static const char* value()
  {
    return "car_interfaces/PositionTask";
  }

  static const char* value(const ::car_interfaces::PositionTask&) { return value(); }
};


// service_traits::MD5Sum< ::car_interfaces::PositionTaskRequest> should match
// service_traits::MD5Sum< ::car_interfaces::PositionTask >
template<>
struct MD5Sum< ::car_interfaces::PositionTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::PositionTask >::value();
  }
  static const char* value(const ::car_interfaces::PositionTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::PositionTaskRequest> should match
// service_traits::DataType< ::car_interfaces::PositionTask >
template<>
struct DataType< ::car_interfaces::PositionTaskRequest>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::PositionTask >::value();
  }
  static const char* value(const ::car_interfaces::PositionTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_interfaces::PositionTaskResponse> should match
// service_traits::MD5Sum< ::car_interfaces::PositionTask >
template<>
struct MD5Sum< ::car_interfaces::PositionTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::PositionTask >::value();
  }
  static const char* value(const ::car_interfaces::PositionTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::PositionTaskResponse> should match
// service_traits::DataType< ::car_interfaces::PositionTask >
template<>
struct DataType< ::car_interfaces::PositionTaskResponse>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::PositionTask >::value();
  }
  static const char* value(const ::car_interfaces::PositionTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_POSITIONTASK_H
