// Generated by gencpp from file car_interfaces/RoadToControl.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_ROADTOCONTROL_H
#define CAR_INTERFACES_MESSAGE_ROADTOCONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace car_interfaces
{
template <class ContainerAllocator>
struct RoadToControl_
{
  typedef RoadToControl_<ContainerAllocator> Type;

  RoadToControl_()
    : path()
    , gear()  {
    }
  RoadToControl_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , gear(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _path_type;
  _path_type path;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _gear_type;
  _gear_type gear;





  typedef boost::shared_ptr< ::car_interfaces::RoadToControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::RoadToControl_<ContainerAllocator> const> ConstPtr;

}; // struct RoadToControl_

typedef ::car_interfaces::RoadToControl_<std::allocator<void> > RoadToControl;

typedef boost::shared_ptr< ::car_interfaces::RoadToControl > RoadToControlPtr;
typedef boost::shared_ptr< ::car_interfaces::RoadToControl const> RoadToControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::RoadToControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::RoadToControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::RoadToControl_<ContainerAllocator1> & lhs, const ::car_interfaces::RoadToControl_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path &&
    lhs.gear == rhs.gear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::RoadToControl_<ContainerAllocator1> & lhs, const ::car_interfaces::RoadToControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::RoadToControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::RoadToControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::RoadToControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::RoadToControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::RoadToControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::RoadToControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::RoadToControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba7de6d6e6f69a4d62782487a2d676e6";
  }

  static const char* value(const ::car_interfaces::RoadToControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba7de6d6e6f69a4dULL;
  static const uint64_t static_value2 = 0x62782487a2d676e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::RoadToControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/RoadToControl";
  }

  static const char* value(const ::car_interfaces::RoadToControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::RoadToControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 发给控制的路 相比nav_msgs/Path 多加了档位，混合A搜索自带档位标志\n"
"\n"
"nav_msgs/Path path\n"
"int32[] gear  #每个点对应档位\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::car_interfaces::RoadToControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::RoadToControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.gear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoadToControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::RoadToControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::RoadToControl_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "path: ";
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gear: ";
    if (v.gear.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.gear.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.gear[i]);
    }
    if (v.gear.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_ROADTOCONTROL_H
