// Generated by gencpp from file car_interfaces/RoadList.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_ROADLIST_H
#define CAR_INTERFACES_MESSAGE_ROADLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <car_interfaces/Pathplan.h>

namespace car_interfaces
{
template <class ContainerAllocator>
struct RoadList_
{
  typedef RoadList_<ContainerAllocator> Type;

  RoadList_()
    : paths()
    , path_length(0)
    , end_points()
    , dis_every_end()  {
    }
  RoadList_(const ContainerAllocator& _alloc)
    : paths(_alloc)
    , path_length(0)
    , end_points(_alloc)
    , dis_every_end(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::car_interfaces::Pathplan_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::car_interfaces::Pathplan_<ContainerAllocator> >> _paths_type;
  _paths_type paths;

   typedef int8_t _path_length_type;
  _path_length_type path_length;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _end_points_type;
  _end_points_type end_points;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _dis_every_end_type;
  _dis_every_end_type dis_every_end;





  typedef boost::shared_ptr< ::car_interfaces::RoadList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::RoadList_<ContainerAllocator> const> ConstPtr;

}; // struct RoadList_

typedef ::car_interfaces::RoadList_<std::allocator<void> > RoadList;

typedef boost::shared_ptr< ::car_interfaces::RoadList > RoadListPtr;
typedef boost::shared_ptr< ::car_interfaces::RoadList const> RoadListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::RoadList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::RoadList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::RoadList_<ContainerAllocator1> & lhs, const ::car_interfaces::RoadList_<ContainerAllocator2> & rhs)
{
  return lhs.paths == rhs.paths &&
    lhs.path_length == rhs.path_length &&
    lhs.end_points == rhs.end_points &&
    lhs.dis_every_end == rhs.dis_every_end;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::RoadList_<ContainerAllocator1> & lhs, const ::car_interfaces::RoadList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::RoadList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::RoadList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::RoadList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::RoadList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::RoadList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::RoadList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::RoadList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b41673bd6f78e4df2d5e654099939f0";
  }

  static const char* value(const ::car_interfaces::RoadList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b41673bd6f78e4dULL;
  static const uint64_t static_value2 = 0xf2d5e654099939f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::RoadList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/RoadList";
  }

  static const char* value(const ::car_interfaces::RoadList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::RoadList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Pathplan[] paths\n"
"int8 path_length\n"
"float32[] end_points\n"
"float32[] dis_every_end\n"
"================================================================================\n"
"MSG: car_interfaces/Pathplan\n"
"Pointplan[] points\n"
"================================================================================\n"
"MSG: car_interfaces/Pointplan\n"
"float64 x\n"
"float64 y\n"
"float64 yaw\n"
"float64 speed\n"
"float64 kappa\n"
"int8 gear\n"
"\n"
;
  }

  static const char* value(const ::car_interfaces::RoadList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::RoadList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.paths);
      stream.next(m.path_length);
      stream.next(m.end_points);
      stream.next(m.dis_every_end);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoadList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::RoadList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::RoadList_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "paths: ";
    if (v.paths.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.paths.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::car_interfaces::Pathplan_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.paths[i]);
    }
    if (v.paths.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "path_length: ";
    Printer<int8_t>::stream(s, indent + "  ", v.path_length);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "end_points: ";
    if (v.end_points.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.end_points.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.end_points[i]);
    }
    if (v.end_points.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dis_every_end: ";
    if (v.dis_every_end.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.dis_every_end.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.dis_every_end[i]);
    }
    if (v.dis_every_end.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_ROADLIST_H
