// Generated by gencpp from file car_interfaces/single_task.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_SINGLE_TASK_H
#define CAR_INTERFACES_MESSAGE_SINGLE_TASK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace car_interfaces
{
template <class ContainerAllocator>
struct single_task_
{
  typedef single_task_<ContainerAllocator> Type;

  single_task_()
    : task_id()
    , bale_num_to_handle(0)
    , destination_shelf_area()
    , origin_shelf_job_position()
    , destination_shelf_job_position()  {
    }
  single_task_(const ContainerAllocator& _alloc)
    : task_id(_alloc)
    , bale_num_to_handle(0)
    , destination_shelf_area(_alloc)
    , origin_shelf_job_position(_alloc)
    , destination_shelf_job_position(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;

   typedef int32_t _bale_num_to_handle_type;
  _bale_num_to_handle_type bale_num_to_handle;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _destination_shelf_area_type;
  _destination_shelf_area_type destination_shelf_area;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _origin_shelf_job_position_type;
  _origin_shelf_job_position_type origin_shelf_job_position;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _destination_shelf_job_position_type;
  _destination_shelf_job_position_type destination_shelf_job_position;





  typedef boost::shared_ptr< ::car_interfaces::single_task_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::single_task_<ContainerAllocator> const> ConstPtr;

}; // struct single_task_

typedef ::car_interfaces::single_task_<std::allocator<void> > single_task;

typedef boost::shared_ptr< ::car_interfaces::single_task > single_taskPtr;
typedef boost::shared_ptr< ::car_interfaces::single_task const> single_taskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::single_task_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::single_task_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::single_task_<ContainerAllocator1> & lhs, const ::car_interfaces::single_task_<ContainerAllocator2> & rhs)
{
  return lhs.task_id == rhs.task_id &&
    lhs.bale_num_to_handle == rhs.bale_num_to_handle &&
    lhs.destination_shelf_area == rhs.destination_shelf_area &&
    lhs.origin_shelf_job_position == rhs.origin_shelf_job_position &&
    lhs.destination_shelf_job_position == rhs.destination_shelf_job_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::single_task_<ContainerAllocator1> & lhs, const ::car_interfaces::single_task_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::single_task_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::single_task_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::single_task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::single_task_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::single_task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::single_task_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::single_task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd39bd39ec0bd232a174cb3a0b3c77c0";
  }

  static const char* value(const ::car_interfaces::single_task_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd39bd39ec0bd232ULL;
  static const uint64_t static_value2 = 0xa174cb3a0b3c77c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::single_task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/single_task";
  }

  static const char* value(const ::car_interfaces::single_task_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::single_task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string task_id\n"
"int32 bale_num_to_handle\n"
"string destination_shelf_area\n"
"geometry_msgs/Pose origin_shelf_job_position\n"
"geometry_msgs/Pose destination_shelf_job_position\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::car_interfaces::single_task_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::single_task_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_id);
      stream.next(m.bale_num_to_handle);
      stream.next(m.destination_shelf_area);
      stream.next(m.origin_shelf_job_position);
      stream.next(m.destination_shelf_job_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct single_task_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::single_task_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::single_task_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bale_num_to_handle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bale_num_to_handle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "destination_shelf_area: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.destination_shelf_area);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "origin_shelf_job_position: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.origin_shelf_job_position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "destination_shelf_job_position: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.destination_shelf_job_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_SINGLE_TASK_H
