// Generated by gencpp from file car_interfaces/StopTask.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_STOPTASK_H
#define CAR_INTERFACES_MESSAGE_STOPTASK_H

#include <ros/service_traits.h>


#include <car_interfaces/StopTaskRequest.h>
#include <car_interfaces/StopTaskResponse.h>


namespace car_interfaces
{

struct StopTask
{

typedef StopTaskRequest Request;
typedef StopTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopTask
} // namespace car_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_interfaces::StopTask > {
  static const char* value()
  {
    return "208d4ab53cf12eb941a7d93b34b7532b";
  }

  static const char* value(const ::car_interfaces::StopTask&) { return value(); }
};

template<>
struct DataType< ::car_interfaces::StopTask > {
  static const char* value()
  {
    return "car_interfaces/StopTask";
  }

  static const char* value(const ::car_interfaces::StopTask&) { return value(); }
};


// service_traits::MD5Sum< ::car_interfaces::StopTaskRequest> should match
// service_traits::MD5Sum< ::car_interfaces::StopTask >
template<>
struct MD5Sum< ::car_interfaces::StopTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::StopTask >::value();
  }
  static const char* value(const ::car_interfaces::StopTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::StopTaskRequest> should match
// service_traits::DataType< ::car_interfaces::StopTask >
template<>
struct DataType< ::car_interfaces::StopTaskRequest>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::StopTask >::value();
  }
  static const char* value(const ::car_interfaces::StopTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_interfaces::StopTaskResponse> should match
// service_traits::MD5Sum< ::car_interfaces::StopTask >
template<>
struct MD5Sum< ::car_interfaces::StopTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::StopTask >::value();
  }
  static const char* value(const ::car_interfaces::StopTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::StopTaskResponse> should match
// service_traits::DataType< ::car_interfaces::StopTask >
template<>
struct DataType< ::car_interfaces::StopTaskResponse>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::StopTask >::value();
  }
  static const char* value(const ::car_interfaces::StopTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_STOPTASK_H
