// Generated by gencpp from file car_interfaces/TargetDetectionInterface.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_TARGETDETECTIONINTERFACE_H
#define CAR_INTERFACES_MESSAGE_TARGETDETECTIONINTERFACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <car_interfaces/Object.h>

namespace car_interfaces
{
template <class ContainerAllocator>
struct TargetDetectionInterface_
{
  typedef TargetDetectionInterface_<ContainerAllocator> Type;

  TargetDetectionInterface_()
    : header()
    , objects()  {
    }
  TargetDetectionInterface_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::car_interfaces::Object_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::car_interfaces::Object_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> const> ConstPtr;

}; // struct TargetDetectionInterface_

typedef ::car_interfaces::TargetDetectionInterface_<std::allocator<void> > TargetDetectionInterface;

typedef boost::shared_ptr< ::car_interfaces::TargetDetectionInterface > TargetDetectionInterfacePtr;
typedef boost::shared_ptr< ::car_interfaces::TargetDetectionInterface const> TargetDetectionInterfaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::TargetDetectionInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::TargetDetectionInterface_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::TargetDetectionInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::TargetDetectionInterface_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "735eae5f7f43274afc03991f37962f29";
  }

  static const char* value(const ::car_interfaces::TargetDetectionInterface_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x735eae5f7f43274aULL;
  static const uint64_t static_value2 = 0xfc03991f37962f29ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/TargetDetectionInterface";
  }

  static const char* value(const ::car_interfaces::TargetDetectionInterface_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# topic : /lidar_camera_det/detections\n"
"# frame_id : velo_link\n"
"std_msgs/Header header  \n"
"Object[] objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: car_interfaces/Object\n"
"float32 conf            # 得分\n"
"float32 class_id        # 类别\n"
"float32 track_id	    # 跟踪id\n"
"float32 x               # 全局 相对加+车辆定位  单位m\n"
"float32 y	            # 全局 相对加+车辆定位  单位m\n"
"float32 z	            # 全局 相对加+车辆定位  单位m\n"
"float32 l_x	            # 相对 单位m\n"
"float32 l_y	            # 相对 单位m\n"
"float32 l_z	            # 相对 单位m\n"
"float32 pitch	        # unit:rad,关于车辆坐标系z轴角度+车辆pitch \n"
"float32 roll	        # unit:rad,关于车辆坐标系y轴角度+车辆roll \n"
"float32 yaw	            # unit:rad,degree+车辆航向 yaw \n"
"float32 degree	        # 角度,车辆坐标系x轴夹角 \n"
"float32 distance	    # 单位m\n"
"float32 height	        # 单位m\n"
"float32 target_width    # 单位m\n"
"float32 target_height   # 单位m\n"
"float32[] left_boudary_point\n"
"float32[] right_boudary_point\n"
"float32[] top_boudary_point\n"
;
  }

  static const char* value(const ::car_interfaces::TargetDetectionInterface_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetDetectionInterface_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::TargetDetectionInterface_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::TargetDetectionInterface_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "objects: ";
    if (v.objects.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::car_interfaces::Object_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.objects[i]);
    }
    if (v.objects.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_TARGETDETECTIONINTERFACE_H
