// Generated by gencpp from file car_interfaces/TaskStsRequest.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_TASKSTSREQUEST_H
#define CAR_INTERFACES_MESSAGE_TASKSTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <car_interfaces/pose.h>

namespace car_interfaces
{
template <class ContainerAllocator>
struct TaskStsRequest_
{
  typedef TaskStsRequest_<ContainerAllocator> Type;

  TaskStsRequest_()
    : order_id()
    , business_type()
    , origin_shelf_area()
    , destination_shelf_area()
    , task_id()
    , bale_num_to_handle(0)
    , task_sts(0)
    , final_pose()  {
    }
  TaskStsRequest_(const ContainerAllocator& _alloc)
    : order_id(_alloc)
    , business_type(_alloc)
    , origin_shelf_area(_alloc)
    , destination_shelf_area(_alloc)
    , task_id(_alloc)
    , bale_num_to_handle(0)
    , task_sts(0)
    , final_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _order_id_type;
  _order_id_type order_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _business_type_type;
  _business_type_type business_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _origin_shelf_area_type;
  _origin_shelf_area_type origin_shelf_area;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _destination_shelf_area_type;
  _destination_shelf_area_type destination_shelf_area;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;

   typedef int8_t _bale_num_to_handle_type;
  _bale_num_to_handle_type bale_num_to_handle;

   typedef int8_t _task_sts_type;
  _task_sts_type task_sts;

   typedef  ::car_interfaces::pose_<ContainerAllocator>  _final_pose_type;
  _final_pose_type final_pose;





  typedef boost::shared_ptr< ::car_interfaces::TaskStsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::TaskStsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TaskStsRequest_

typedef ::car_interfaces::TaskStsRequest_<std::allocator<void> > TaskStsRequest;

typedef boost::shared_ptr< ::car_interfaces::TaskStsRequest > TaskStsRequestPtr;
typedef boost::shared_ptr< ::car_interfaces::TaskStsRequest const> TaskStsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::TaskStsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::TaskStsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::TaskStsRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::TaskStsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.order_id == rhs.order_id &&
    lhs.business_type == rhs.business_type &&
    lhs.origin_shelf_area == rhs.origin_shelf_area &&
    lhs.destination_shelf_area == rhs.destination_shelf_area &&
    lhs.task_id == rhs.task_id &&
    lhs.bale_num_to_handle == rhs.bale_num_to_handle &&
    lhs.task_sts == rhs.task_sts &&
    lhs.final_pose == rhs.final_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::TaskStsRequest_<ContainerAllocator1> & lhs, const ::car_interfaces::TaskStsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::TaskStsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::TaskStsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::TaskStsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::TaskStsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::TaskStsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::TaskStsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::TaskStsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f3da65652253ee78f636a2aef7c03f5";
  }

  static const char* value(const ::car_interfaces::TaskStsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f3da65652253ee7ULL;
  static const uint64_t static_value2 = 0x8f636a2aef7c03f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::TaskStsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/TaskStsRequest";
  }

  static const char* value(const ::car_interfaces::TaskStsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::TaskStsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string order_id\n"
"string business_type\n"
"string origin_shelf_area\n"
"string destination_shelf_area\n"
"string task_id\n"
"int8 bale_num_to_handle\n"
"int8 task_sts\n"
"car_interfaces/pose final_pose\n"
"\n"
"================================================================================\n"
"MSG: car_interfaces/pose\n"
"std_msgs/Header header\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 pitch\n"
"float32 roll\n"
"float32 yaw\n"
"bool state\n"
"bool slam_reliability\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::car_interfaces::TaskStsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::TaskStsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order_id);
      stream.next(m.business_type);
      stream.next(m.origin_shelf_area);
      stream.next(m.destination_shelf_area);
      stream.next(m.task_id);
      stream.next(m.bale_num_to_handle);
      stream.next(m.task_sts);
      stream.next(m.final_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskStsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::TaskStsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::TaskStsRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "order_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.order_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "business_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.business_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "origin_shelf_area: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.origin_shelf_area);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "destination_shelf_area: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.destination_shelf_area);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bale_num_to_handle: ";
    Printer<int8_t>::stream(s, indent + "  ", v.bale_num_to_handle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_sts: ";
    Printer<int8_t>::stream(s, indent + "  ", v.task_sts);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "final_pose: ";
    Printer< ::car_interfaces::pose_<ContainerAllocator> >::stream(s, indent + "  ", v.final_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_TASKSTSREQUEST_H
