// Generated by gencpp from file car_interfaces/TaskSts.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_TASKSTS_H
#define CAR_INTERFACES_MESSAGE_TASKSTS_H

#include <ros/service_traits.h>


#include <car_interfaces/TaskStsRequest.h>
#include <car_interfaces/TaskStsResponse.h>


namespace car_interfaces
{

struct TaskSts
{

typedef TaskStsRequest Request;
typedef TaskStsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TaskSts
} // namespace car_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_interfaces::TaskSts > {
  static const char* value()
  {
    return "8a6ad011433f39152e544540da918dee";
  }

  static const char* value(const ::car_interfaces::TaskSts&) { return value(); }
};

template<>
struct DataType< ::car_interfaces::TaskSts > {
  static const char* value()
  {
    return "car_interfaces/TaskSts";
  }

  static const char* value(const ::car_interfaces::TaskSts&) { return value(); }
};


// service_traits::MD5Sum< ::car_interfaces::TaskStsRequest> should match
// service_traits::MD5Sum< ::car_interfaces::TaskSts >
template<>
struct MD5Sum< ::car_interfaces::TaskStsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::TaskSts >::value();
  }
  static const char* value(const ::car_interfaces::TaskStsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::TaskStsRequest> should match
// service_traits::DataType< ::car_interfaces::TaskSts >
template<>
struct DataType< ::car_interfaces::TaskStsRequest>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::TaskSts >::value();
  }
  static const char* value(const ::car_interfaces::TaskStsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_interfaces::TaskStsResponse> should match
// service_traits::MD5Sum< ::car_interfaces::TaskSts >
template<>
struct MD5Sum< ::car_interfaces::TaskStsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_interfaces::TaskSts >::value();
  }
  static const char* value(const ::car_interfaces::TaskStsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_interfaces::TaskStsResponse> should match
// service_traits::DataType< ::car_interfaces::TaskSts >
template<>
struct DataType< ::car_interfaces::TaskStsResponse>
{
  static const char* value()
  {
    return DataType< ::car_interfaces::TaskSts >::value();
  }
  static const char* value(const ::car_interfaces::TaskStsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_TASKSTS_H
