// Generated by gencpp from file car_interfaces/Yolov5DetectionInterface.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_YOLOV5DETECTIONINTERFACE_H
#define CAR_INTERFACES_MESSAGE_YOLOV5DETECTIONINTERFACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_interfaces
{
template <class ContainerAllocator>
struct Yolov5DetectionInterface_
{
  typedef Yolov5DetectionInterface_<ContainerAllocator> Type;

  Yolov5DetectionInterface_()
    : timestamp(0.0)
    , bbox()
    , conf()
    , class_id()
    , mask()
    , tray_degree()
    , tray_distance()
    , tray_height()
    , tray_x()
    , tray_y()
    , tray_z()
    , tray_yaw()  {
    }
  Yolov5DetectionInterface_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , bbox(_alloc)
    , conf(_alloc)
    , class_id(_alloc)
    , mask(_alloc)
    , tray_degree(_alloc)
    , tray_distance(_alloc)
    , tray_height(_alloc)
    , tray_x(_alloc)
    , tray_y(_alloc)
    , tray_z(_alloc)
    , tray_yaw(_alloc)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _bbox_type;
  _bbox_type bbox;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _conf_type;
  _conf_type conf;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _class_id_type;
  _class_id_type class_id;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _mask_type;
  _mask_type mask;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tray_degree_type;
  _tray_degree_type tray_degree;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tray_distance_type;
  _tray_distance_type tray_distance;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tray_height_type;
  _tray_height_type tray_height;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tray_x_type;
  _tray_x_type tray_x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tray_y_type;
  _tray_y_type tray_y;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tray_z_type;
  _tray_z_type tray_z;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tray_yaw_type;
  _tray_yaw_type tray_yaw;





  typedef boost::shared_ptr< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> const> ConstPtr;

}; // struct Yolov5DetectionInterface_

typedef ::car_interfaces::Yolov5DetectionInterface_<std::allocator<void> > Yolov5DetectionInterface;

typedef boost::shared_ptr< ::car_interfaces::Yolov5DetectionInterface > Yolov5DetectionInterfacePtr;
typedef boost::shared_ptr< ::car_interfaces::Yolov5DetectionInterface const> Yolov5DetectionInterfaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.bbox == rhs.bbox &&
    lhs.conf == rhs.conf &&
    lhs.class_id == rhs.class_id &&
    lhs.mask == rhs.mask &&
    lhs.tray_degree == rhs.tray_degree &&
    lhs.tray_distance == rhs.tray_distance &&
    lhs.tray_height == rhs.tray_height &&
    lhs.tray_x == rhs.tray_x &&
    lhs.tray_y == rhs.tray_y &&
    lhs.tray_z == rhs.tray_z &&
    lhs.tray_yaw == rhs.tray_yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ee1970563c4a57e5269f962cf6b7df0";
  }

  static const char* value(const ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ee1970563c4a57eULL;
  static const uint64_t static_value2 = 0x5269f962cf6b7df0ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/Yolov5DetectionInterface";
  }

  static const char* value(const ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64  timestamp     # 数据帧时间戳\n"
"#std_msgs/Header header   后续加入 坐标系信息\n"
"float32[] bbox   	# 4 个一组    \n"
"float32[] conf		# 1 个一组\n"
"float32[] class_id	# 1\n"
"float32[] mask		# 32\n"
"\n"
"float32[] tray_degree\n"
"float32[] tray_distance\n"
"float32[] tray_height\n"
"\n"
"float32[] tray_x\n"
"float32[] tray_y\n"
"float32[] tray_z\n"
"float32[] tray_yaw\n"
;
  }

  static const char* value(const ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.bbox);
      stream.next(m.conf);
      stream.next(m.class_id);
      stream.next(m.mask);
      stream.next(m.tray_degree);
      stream.next(m.tray_distance);
      stream.next(m.tray_height);
      stream.next(m.tray_x);
      stream.next(m.tray_y);
      stream.next(m.tray_z);
      stream.next(m.tray_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Yolov5DetectionInterface_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::Yolov5DetectionInterface_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox: ";
    if (v.bbox.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.bbox.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.bbox[i]);
    }
    if (v.bbox.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "conf: ";
    if (v.conf.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.conf.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.conf[i]);
    }
    if (v.conf.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "class_id: ";
    if (v.class_id.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.class_id.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.class_id[i]);
    }
    if (v.class_id.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mask: ";
    if (v.mask.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.mask.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.mask[i]);
    }
    if (v.mask.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tray_degree: ";
    if (v.tray_degree.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.tray_degree.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.tray_degree[i]);
    }
    if (v.tray_degree.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tray_distance: ";
    if (v.tray_distance.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.tray_distance.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.tray_distance[i]);
    }
    if (v.tray_distance.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tray_height: ";
    if (v.tray_height.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.tray_height.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.tray_height[i]);
    }
    if (v.tray_height.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tray_x: ";
    if (v.tray_x.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.tray_x.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.tray_x[i]);
    }
    if (v.tray_x.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tray_y: ";
    if (v.tray_y.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.tray_y.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.tray_y[i]);
    }
    if (v.tray_y.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tray_z: ";
    if (v.tray_z.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.tray_z.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.tray_z[i]);
    }
    if (v.tray_z.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tray_yaw: ";
    if (v.tray_yaw.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.tray_yaw.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.tray_yaw[i]);
    }
    if (v.tray_yaw.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_YOLOV5DETECTIONINTERFACE_H
